keyboardio/Chrysalis

- .babelrc
- .eslintrc.js
- .stylelintrc.json
- config/jest/cssTransform.js
- config/jest/fileTransform.js
- electron-webpack.json
- jest.config.js
- package.json
- src/main/index.js
- src/renderer/App.test.js
- src/renderer/Key.js
- src/renderer/KeyLayout.js
- src/renderer/Layer.js
- src/renderer/__snapshots__/App.test.js.snap
- src/renderer/app.js
- src/renderer/index.js
- src/renderer/keymap-transformer.js
- src/renderer/keymap.css
- src/renderer/mockup/components/ImportExport.js
- src/renderer/mockup/components/KeymapEditor.js
- src/renderer/mockup/components/LayerControls.js
- src/renderer/mockup/components/LedEditor.js
- src/renderer/mockup/components/PluginPicker.js
- src/renderer/mockup/components/Plugins.js
- src/renderer/mockup/components/Tab.js
- src/renderer/mockup/components/TabBar.js
- src/renderer/mockup/components/TabButton.js
- src/renderer/mockup/components/Update.js
- wallaby.config.js
- yarn.lock
This PR adds the following things:
Code style:
Prettier for automatic code styling. (`yarn prettify`)
eslint for linting JS (`yarn lint:js`)
`yarn clean:code` will run both Prettier and eslint scripts together
Stylelint for linting css (`yarn lint:css`)
`yarn lint:all` will lint both js and css
Testing: (`yarn test` `yarn test:watch`)
Jest testing library for unit and integration testing
react-testing-library for test helper functions
The Husky library was added for git hooks. This now runs a pre-commit hook which will run eslint and tests on each commit in order to catch problems. It can be bypassed with a `--no-verify` flag on a commit.
> Add tooling - Prettier, eslint, Stylelint, Jest

- package.json
- src/errors/errors.js
- src/renderer/App.js
- yarn.lock
Add `tweetnacl` package explicitly to stop Yarn error with Electron.
Fix eslint and prettier errors.
> Fix electron/yarn subdependency and eslint/prettier errors

- .eslintrc.js
- src/renderer/App.js
Given the recent push for more logging with a view to getting functional on mac, temporarily enabling console in the linter and remove the visual noise of lint escape messages
> Fixed linting error

- src/main/index.js
- src/renderer/__snapshots__/App.test.js.snap
- src/renderer/components/KeyboardSelect.js
- src/renderer/components/Settings.js
By default, start with DevTools disabled. Add a toggler onto the KeyboardSelect and Settings components.
Fixes #42.
> Do not pop up the DevTools by default

- package.json
- src/renderer/App.js
- src/renderer/__snapshots__/App.test.js.snap
- src/renderer/components/Dashboard.js
- src/renderer/components/KeyboardSelect.js
- yarn.lock
This moves the DevTools toggle and the bugreport link into an always-visible Speed Dial, so that the handling of them can be implemented globally, instead of for every component that needs to access it.
As a bonus, it also adds a dumb screenshot tool.
> Speed dial for some persistent actions

- src/renderer/components/ColormapEditor.js
- src/renderer/components/LayoutEditor.js
- src/styles/keymap.css
Moves the "Save changes" button to a better place on both the Colormap and Keymap editors (fixes #50), removes the stepper from the Keymap editor loader (#49), makes the keymap smaller on 1024x768 resolutions (#51).
> Various UI fixes

- src/renderer/Error.js
When we encounter an error during startup, display an error page telling the user to see the development console, and to file a bug. This is not ideal, but way better than an empty white screen without any other indication.
Fixes #57,
> Handle early errors gracefully

- src/renderer/App.js
When one clicks the speed dial, it should stay open until clicked again, instead of closing whenever the mouse leaves it.
Fixes #52.
> Clicking the speed dial should keep it open

- src/renderer/App.js
In the main app, listen to USB detach events, and if we find that a device with our own VID/PID got detached, check `focus._port.isOpen` to see if it was us. If it was, then display a warning, close the port forcibly, and go back to the keyboard selection screen.
Fixes #31.
> Improved detach handling

- src/renderer/App.js
- yarn.lock
On OSX, we need to set `clocal` on the serial port, do that by spawning `stty` (cheaper than pulling in yet another npm module). This fixes the read timeouts and garbage reading. To fix writes, update to the newest chrysalis-focus, which includes an OSX workaround.
Fixes #65.
> Fix serial communication on OSX

- src/renderer/components/Dashboard.js
If we detected that the keyboard supports keymap editing, default to that page.
Fixes #87.
> Dashboard: Default to the keymap page, if available

- src/renderer/components/LayoutEditor.js
- src/renderer/components/LayoutEditor/KeySelector.js
These changes make read-only keymaps uneditable, fixing #79, and also mark them `(RO)` in the tab bar, fixing #86.
> Various keymap editor fixes

- src/renderer/App.js
- src/renderer/__snapshots__/App.test.js.snap
- src/renderer/components/AppTools.js
This turns the FAB SpeedDial into a menu that's always on the lower right corner, and functions like a proper menu.
This is done in a three step process:
- First we extract the Tools speed dial into its own component.
- Then we turn it from a FAB into a Menu.
- Then we make it not toggle DevTools, because that's counter-intuitive.
The end result looks like this:
Fixes #78.
> Turn the FAB SpeedDial into a persistent menu

- src/renderer/App.js
- src/renderer/components/Dashboard.js
- src/renderer/components/KeyboardInfo.js
- src/renderer/components/KeyboardInfo/UploadDialog.js
When clicking the "Upload" button on the flashing card, instead of flashing right away, a dialog will pop up with some explanatory text about what will happen, and what to expect. This fixes #83.
After flashing is done, we'll fall back to the keyboard selection screen, because reconnecting is not reliable yet. This should fix the white screen after flashing, and as such, this also closes #69.
> Completely revamped flashing flow

- src/renderer/App.js
- src/renderer/components/KeyboardInfo.js
- src/renderer/components/KeyboardInfo/UploadDialog.js
Reset the keyboard ourselves, with higher timeouts than `AvrGirl`. This seems to help with flashing failing at the post-reset stage, thus fixes #93.
We also go back to the keyboard selection page with a success message after a successful flash, the `SaveChangesButton` thus does not have time to revert back to active. This fixes #94.
> Flasher: Vastly improved robustness

- src/renderer/components/KeyboardInfo.js
When querying the version and Focus throws an error, catch that, so we can disable the progress bar.
Fixes #84.
> KeyboardInfo: Handle errors from focus.command("version")

- src/renderer/App.js
Not needing the CDC patch anymore, we do not need such high (15s) timeouts, and
the default 5s should suffice.
> App: Use the default timeout for Focus

- src/renderer/components/LayoutEditor/KeySelector.js
Unlike some of the other components, `KeyGroupT` is a function, thus, we need to use `props`, not `this.props`.
> KeySelector: Fix KeyGroupT's support for disabled states

- src/renderer/components/LayoutEditor/KeySelector.js
This limits us to the number of macros supported by `@chrysalis-api/keymap` (currently 32), but makes it possible to change them. Until we find a better pattern to do the same, this will do.
Fixes #62.
> KeySelector: Use the default grid for Macros

- src/renderer/App.js
- src/renderer/__snapshots__/App.test.js.snap
- src/renderer/components/ColormapEditor.js
- src/renderer/components/ColormapEditor/ColorBox.js
- src/renderer/components/KeyboardSelect.js
- src/renderer/components/LayoutEditor.js
- src/renderer/components/LayoutEditor/KeySelector.js
In cases where we used a `<div>` only to return multiple elements (and not for grouping), use `<React.Fragment>` instead. This cuts down the size of the DOM a bit, and we won't have completely unnecessary divs all around.
Fixes #111.
> Use React.Fragment wherever appropriate

- src/main/index.js
If, for some reason, the renderer process crashes, we can't display a proper error message in the browser window, so log one to the terminal with a few instructions about how to file a useful bug report about it.
This does not fix #112, but in the event of a similar bug occurring, we'll have more clue and more information to start with.
> main: Catch the gpu-process-crashed event, and print a message

- src/renderer/screens/ColormapEditor.js
- src/renderer/screens/ColormapEditor/Layer.js
- src/renderer/screens/LayoutEditor.js
With the last big UI overhaul, the progress bars on the editor screens were broken (they stopped being displayed). This restores them, and even improves the experience: we now show an empty keymap/colormap while loading, with a progressbar attached to the bottom of the appbar.
> Progressbar fixes

- src/renderer/__snapshots__/App.test.js.snap
- src/renderer/screens/KeyboardSelect.js
Depending on whether we found keyboards or not, color the "Scan devices" button green or red for a short while (a second) upon completion, to provide some feedback that the button does something.
Fixes #129.
> KeyboardSelect: Color the "Scan devices" button green or red

- src/renderer/components/SaveChangesButton.js
In the end, we want the button to be floating, ie, fixed to the bottom right corner of the screen, no matter what.
This is still not ideal, but marginally better than the current behaviour.
> SaveChangesButton: Make it fixed

- src/renderer/components/SaveChangesButton.js
- src/renderer/screens/LayoutEditor.js
- src/renderer/screens/LayoutEditor/KeySelector.js
Instead of having a good few number of different ways to lay out the selectable keys on the right side of the keymap, move it to the bottom, and present the list as a simple list of buttons one after another. The only exception are unknown keycodes, those are still presented as a numeric input field.
This fixes #120, and is based on top of #137, because otherwise the save changes button forces a scrollbar on us.
I kept the type selector as a menu to be clicked instead of inlining it and having an embedded scrollbar there, because this *felt* better.
> KeySelector: Major redesign

- NEWS.md
- src/renderer/App.js
- src/renderer/screens/FirmwareUpdate.js
- src/renderer/screens/KeyboardSelect.js
- src/renderer/screens/Welcome.js
We support a number of keyboards that do not come with Kaleidoscope by default, and their factory firmware doesn't have a virtual serial port enabled either. We weren't able to find these previously, making it that much harder to try Chrysalis with a supported device.
With this change, we do a second pass of search, for keyboards that aren't Kaleidoscope-powered out of the factory, and find them via the `usb` library. For these boards, we do not really "connect" to them, just set things up well enough for the `FirmwareUpdate` and `Welcome` screens to work. This in turn allows one to flash a Kaleidoscope-based firmware onto these boards, and try Chrysalis.
We do make an assumption that all connected keyboards are unique, that we do not have two of the same keyboard attached at the same …
> Support FirmwareUpdate & Welcome for non-Kaleidoscope firmware

- NEWS.md
- package.json
- src/renderer/screens/LayoutEditor/KeySelector.js
- yarn.lock
When encountering a modded key (`LSHIFT()` & friends), display the un-modded group. In the key list, look at the keycode, and handle modifiers. When selecting a key via the buttons, apply the selected modifiers too.
In practice, this means we can toggle the modifiers on and off now, and this fixes #63.
> KeySelector: Add support for moddable keys

- src/renderer/screens/LayoutEditor/KeySelector.js
- src/styles/keymap.css
> Use a monospace font for keys and key buttons

- src/renderer/screens/LayoutEditor/KeySelector.js
When changing the key type, we want to start from a clean slate, as if no key was selected before. For this reason, track the keycode twice, so to say: we keep a state of what's selected (`actualKeycode`), and in props, what's effective on the keymap (`currentKeyCode`).
Fixes #158.
> KeySelector: Fix key type changing

- src/renderer/screens/ColormapEditor.js
- src/renderer/screens/ColormapEditor/Palette.js
- src/renderer/screens/LayoutEditor.js
- src/renderer/screens/LayoutEditor/KeySelector.js
Layers fade in, the key selector slides up, and the color picker fades in too.
Fixes #168.
> Use transitions for components that appear/disappear

- package.json
- src/renderer/App.js
- src/renderer/screens/LayoutEditor/KeySelector.js
- src/styles/keymap.css
- yarn.lock
Bundle the "Roboto" and "Source Code Pro" fonts we use in the application (the latter replaces "Input Mono", which I didn't find a package for).
Fixes #159.
> Bundle the fonts we use

- src/renderer/i18n/en.js
- src/renderer/i18n/hu.js
- src/renderer/screens/Welcome.js
If we're connected to a keyboard with a serial port, but did not find Chrysalis, there's a small chance that we connected while the keyboard was booting up, or while something else was reading from the port too. In this case, offer an easy way to reconnect.
If we're connected to a board without a serial port, we do not offer the reconnect.
Fixes #157.
> Welcome: Implement a "Reconnect" button

- src/renderer/screens/ColormapEditor.js
- src/renderer/screens/LayoutEditor.js
When copying a layer, do a deep copy instead of simple assignment. With a simple assignment, when we edit the copied layer, the source would change too, as they are the same array object under the hood. With a deep copy, they're separate, as they should be.
> Fix layer copying

- src/renderer/components/SaveChangesButton.js
- src/renderer/screens/FirmwareUpdate.js
This makes the icon settable by the caller, so we can use different ones for different purposes (such as one for the firmware upgrade button, and another for the layout/colormap save). It also makes the default icon `Sync` instead of `SaveAlt`, because the latter was too easy to interpret as downloading, which isn't what it does.
Furthermore, when in floating mode, display the FAB part only.
> A few SaveChangesButton updates

- src/renderer/i18n/en.js
- src/renderer/i18n/hu.js
- src/renderer/screens/LayoutEditor/KeySelector.js
Adds support for DualUse keys to the Key Selector component.
Fixes #76.
When looking at a DualUse modifier key, one can toggle DualUse off, DualUse Layers are disabled. Selecting a different modifier selects that one only. `AltGr` is disabled, because that's not supported by DualUse at t he moment.
When looking at a DualUse layer key, modifiers are not shown, and dual-use can toggle off.
Looking at a modded key, dual-use can be turned on (unless the modifier is `AltGr`).
Multiple modifiers selected? DualUse is not an option then.
For a normal key, we offer a modifier bar with dual-use disabled until a modifier is selected. We also offer a dual-use layer option, which defaults to switching to layer 0 first.
> KeySelector: Implement support for DualUse keys

- src/renderer/screens/LayoutEditor.js
When initially displaying the LayoutEditor screen, start with the default layer's tab selected.
Fixes #186.
> LayoutEditor: Initialize to the default layer (if set)

- src/renderer/screens/LayoutEditor.js
When clearing the layer, don't fill the array with zeros, but with objects with their `keyCode` property set to zero - this is the structure the layout editor expects.
> LayoutEditor: Fix layer clearing

- src/renderer/screens/LayoutEditor.js
We only want to switch to the default layer when the component is mounted, not when properties update or when we rescan the keyboard for some other reason. Thus, move the `currentLayer` setting to `componentDidMount()`.
Fixes #195.
> LayoutEditor: Only switch to the default layer on mount

- src/renderer/i18n/en.js
- src/renderer/i18n/hu.js
- src/renderer/screens/FirmwareUpdate.js
We should let users know where to find the sources of the bundled default firmware files, and where to find them.
> FirmwareUpdate: Mention the firmware bundle repo

- src/renderer/i18n/en.js
- src/renderer/i18n/hu.js
- src/renderer/screens/KeyboardSelect.js
There are cases where one wants to disconnect from the keyboard without exiting Chrysalis and without changing to another keyboard. For this reason, the `Connect` button on the `KeyboardSelector` screen will turn into `Disconnect` when the selected device is the one we're connected to (assuming we have Serial open). To make this easier, the `KeyboardSelector` screen now defaults to showing the opened device on mount instead of the first one found.
> Provide a way to disconnect from the keyboard

- src/renderer/screens/LayoutEditor/KeySelector.js
This reverts commit 727fdbf2ba350ed155e61a0ef234f23d34ee95d0, fixes #198, and reopens #119.
Signed-off-by: Gergely Nagy <algernon@keyboard.io>
> Revert "KeySelector: Select keys based on keys pressed"

- src/renderer/screens/ColormapEditor.js
- src/renderer/screens/LayoutEditor.js
Without this, the main menu will not turn into a contextual alternate, and we won't be able to easily cancel the clear or the copy.
> When clearing or copying a layer, start the context state

- src/renderer/i18n/en.js
- src/renderer/i18n/hu.js
- src/renderer/screens/ColormapEditor.js
- src/renderer/screens/LayoutEditor.js
Copying layers from another one is a much more straightforward operation than copying to, primarily because we're on the layer to be destroyed when we begin. As such, there's less chance of shooting ourselves in the face.
Fixes #226.
> Editors: Copy layers from, not to

- src/renderer/i18n/en.js
- src/renderer/i18n/hu.js
- src/renderer/screens/KeyboardSelect.js
- "Scan devices" became "Scan keyboards" (#212)
- "Scan devices" is outlined by default (#211)
- The selector became a real dropdown (#214)
- The icon has been integrated into the dropdown
Keyboards that have a serial port are in the secondary color, keyboards that do not, are grey.
- The error message uses the same typeface as everything else (#213)
> KeyboardSelector UI improvements

- src/renderer/i18n/en.js
- src/renderer/i18n/hu.js
- The call to action button is much more to the point (#216)
- The explanatory text is also shorter and to the point: just explain why we're on this screen, and let the followup screen do the rest (#217)
This does not address #218, that's a bit more involved than changing text, and requires slightly deeper changes, so I will address it in a separate PR.
> Welcome screen: UI improvements

- src/renderer/screens/ColormapEditor.js
- src/renderer/screens/LayoutEditor.js
When we clear a layer, we want to set it back to its default state with an empty EEPROM, which is all bits set.
Fixes #209.
> When clearing layers, clear to unspecified instead of zero

- src/renderer/i18n/en.js
- src/renderer/i18n/hu.js
- src/renderer/screens/FirmwareUpdate.js
- The title text is gone, the screen title is sufficient (#222)
- The text has been simplified, pretty much replaced (#222)
- The selector is a dropdown now (#220)
- The default firmware is now better specified and less ambigous (#219)
> FirmwareUpdate: UI improvements

- src/renderer/screens/FirmwareUpdate.js
When done with flashing, either successfully or not, we go back to the keyboard selection screen. At this point, the keyboard should not appear connected, because it really isn't.
This partially addresses #224.
> FirmwareUpdate: Disconnect after a successful flash too

- package.json
- src/renderer/screens/KeyboardSelect.js
- yarn.lock
This is similar in spirit to #241, except it doesn't have a factory firmware, so one will be able - and forced - to select their own, based on what keyboard they have. This allows Chrysalis to flash any Teensy board with any firmware.
We'll have a nice explanation on the firmware update screen, once #221 is in place.
> hardware: Add (flashing) support for generic Teensy devices

- package.json
- src/renderer/i18n.js
- src/renderer/screens/FirmwareUpdate.js
- src/renderer/screens/KeyboardSelect.js
- yarn.lock
First we make the `i18n` system able to refresh parts of the localised text, by pulling it from the current hardware library. Then, the `FirmwareUpdate` screen can display device-specific update instructions. Finally, we transition to the new `@chrysalis-api/hardware` library, which collects all the hardware libraries we have - this makes it easier to upgrade all of them in one fell swoop.
Fixes #221.
> Support device-specific text on the FirmwareUpdate screen

- src/renderer/i18n/en.js
- src/renderer/i18n/hu.js
- src/renderer/screens/FirmwareUpdate.js
We plan to narrow down the scope of the default firmware shipped with Chrysalis to avoid surprises, and to be closer to factory defaults. However, we'd still like to offer something with more bells and whistles - an experimental firmware.
Teach FirmwareUpdate to handle both, along with custom firmware.
> FirmwareUpdate: Add support for experimental firmware

- package.json
- src/renderer/App.js
- src/renderer/i18n/en.js
- src/renderer/i18n/hu.js
- src/renderer/screens/LayoutEditor.js
- yarn.lock
This is a major update to the LayoutEditor, which updates it to support the default/custom split on the protocol level. While there, added the option to hide default layers, and to set the `keymap.onlyCustom` flag too.
We also copy the default layers into EEPROM and toggle onlyCustom on if we see that the EEPROM layers are all transparent.
Fixes #228.
See screenshots [here](https://github.com/keyboardio/Chrysalis/issues/228#issuecomment-457874928)
> LayoutEditor: Update for the default/custom split

- package.json
- src/renderer/screens/KeyboardSelect.js
- yarn.lock
There are keyboards out there that share VID+PID with another. Instead of trying to choose one, or autodetect which one we have, place both onto the list, and let the end-user select the right one.
This requires an update to `@chrysalis-api/focus`, to a version that supports this case too.
> KeyboardSelect: Support devices that share the same VID+PID

- tools/s3-upload.js
On a successful upload, redirect `Chrysalis/latest/Chrysalis.$EXTENSION` to the current upload. This gives us a static URL that always points to the latest artifact.
> tools/s3-upload: Redirect Chrysalis/latest/Chrysalis.*

- package.json
- src/renderer/App.js
- src/renderer/screens/LayoutEditor.js
- yarn.lock
This fixes a few issues with `LayoutEditor`, in case we aren't using `keymap.onlyCustom` (affects both legacy and current firmware). It also updates the `@chrysalis-api/keymap` library (which supports legacy firmware now). A few checks were also updated to allow displaying the layout editor even when the keyboard runs an older firmware.
Fixes #271.
> LayoutEditor update to support legacy firmware

- README.md
This adds an AppImage & DMG download badge, now that we have automatic builds for those two.
> README: Add AppImage & DMG downloads for the latest build

- .travis.yml
Disable `filter_secrets`, which hopefully makes our windows builds work. In general, this wouldn't be a safe thing, because a malicious pull request could leak our secrets. But we only run builds for master, not for pull requests or any other branch, so what we do is well controlled, and shouldn't leak any.
> travis: Disable filter_secrets

- package.json
- src/renderer/i18n/en.js
- src/renderer/i18n/hu.js
- src/renderer/screens/LayoutEditor.js
- src/renderer/screens/Settings.js
- yarn.lock
Now that we copy the built-in layers to EEPROM when we encounter an uninitialized EEPROM, having the default layer selector on the layer bar is not needed. Moved it to the Settings page. Fixes #288.
Similarly, selecting whether to use custom layers only or not belongs in Settings too. Fixes #286.
Likewise, whether to show or hide the default / built-in layers is also a setting, and belongs there. Since this is not saved on the keyboard, but we want to persist the setting, we're using `electron-settings` to store the setting on disk. Fixes #287 and fixes #277.
The moved settings do not take effect immediately like they used to, one needs to use the new "Save changes" button on the page. Fixes #285.
This also fixes #194, due to having figured out how to store settings.
> Move a few less-than-common settings from LayoutEditor to Settings

- src/renderer/App.js
- src/renderer/components/MainMenu/ChatMenuItem.js
- src/renderer/components/MainMenu/ColormapMenuItem.js
- src/renderer/components/MainMenu/ExitMenuItem.js
- src/renderer/components/MainMenu/FeedbackMenuItem.js
- src/renderer/components/MainMenu/FlashMenuItem.js
- src/renderer/components/MainMenu/KeyboardSelectMenuItem.js
- src/renderer/components/MainMenu/KeyboardSettingsMenuItem.js
- src/renderer/components/MainMenu/KeymapMenuItem.js
- src/renderer/components/MainMenu/MainMenu.js
- src/renderer/components/MainMenu/PreferencesMenuItem.js
- src/renderer/components/MainMenu/SettingsMenuItem.js
- src/renderer/components/MainMenu/WelcomeMenu.js
- src/renderer/i18n/en.js
- src/renderer/i18n/hu.js
- src/renderer/screens/KeyboardSettings.js
- src/renderer/screens/Preferences.js
Lift out the keyboard settings from the Settings menu, and place them into their own screen. For clarity, we add subtitles to the side menu too.
The lift is achieved in three steps:
- Adding subtitles to the drawer
- Renaming `Settings` to `Preferences`
- Lifting out `Keyboard Settings` from `Preferences`
Keyboard settings start with the "Advanced" settings exposed for now.
We're back to the older preferences, with no keyboard-related stuff.
> Split "Keyboard settings" out of "Settings"

- src/renderer/App.js
- src/renderer/screens/KeyboardSelect.js
- src/renderer/screens/Welcome.js
This should fix the remaining issues where we navigate somewhere that depends on focus being in one state, but isn't yet.
Fixes #302.
> When navigating, always await for it to finish

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- README.md
This adds GitHub issue templates for bugs & feature requests. These include a bit of guidance about what we need to deal with them (like explaining how to collect logs from the developer console in case of a bug report).
It also updates the README to encourage filing issues.
> Add issue templates

- src/renderer/components/Header.js
- src/renderer/components/SaveChangesButton.js
Instead of having a "Sync" icon, make it an arrow, to resemble the Arduino IDE more. The button now has a tooltip too, if it is a floating button without the text part.
Furthermore, the color was changed to "primary", and as a consequence, the AppBar changed its in-context color to "secondary".
Fixes #296.
> SaveChangesButton: Change the icon to something more obvious

- src/renderer/screens/LayoutEditor.js
On our initial render, we are supposed to show the default layer. However, if the default layer is a hardcoded one, and we have those hidden, we can't. In this case, show the first custom layer instead.
Fixes #301.
> LayoutEditor: Make the initial layer selection more robust

- src/renderer/App.js
- src/renderer/screens/KeyboardSelect.js
We should be navigating to `/layout-editor` or `/welcome`, not `./layout-editor` or `./welcome`. The distinction is important, the router doesn't know how to handle the latter ones.
Fixing this navigation means we do not need the one in KeyboardSelect anymore.
These two together restore the functionality of landing on the Welcome screen when Focus wasn't detected on the keyboard.
> App.js: Fix onKeyboardConnect()'s navigate targets

- src/renderer/components/MainMenu/MainMenu.js
- src/renderer/components/MainMenu/UpgradeMenuItem.js
- src/renderer/i18n/en.js
- src/renderer/i18n/hu.js
- src/renderer/utils/getLatestVersion.js
If there's a new version of Chrysalis available (detected once on startup), display an upgrade notice in the main menu, below the Chrysalis version.
Fixes #314.
Opens a direct link to the latest version (not to the latest symlink), so it is saved with a versioned filename.
> MainMenu: If there's a new version of Chrysalis. notify the user

- src/renderer/components/ConfirmationDialog.js
- src/renderer/i18n/en.js
- src/renderer/i18n/hu.js
- src/renderer/screens/Editor.js
- src/renderer/screens/KeyboardSettings.js
EEPROM is cleared by pulling contents first, and replacing every byte with 255, so the same code will work for any size of EEPROM. It's perhaps a bit wasteful to do this, but it's always correct.
Fixes #283.
> Add a way to reset EEPROM

- src/renderer/App.js
- src/renderer/screens/KeyboardSettings.js
When there are pending changes, display the in-context AppBar. This allows us to cancel pending changes.
> KeyboardSettings: Support the in-context appbar

- src/renderer/components/MainMenu/MainMenu.js
When we navigate imperatively, without using `MainMenu`'s `setCurrentPage`, `currentPage` becomes stale. Use the global history instead of local state to make sure the sidebar always shows the right screen.
Fixes #312.
> MainMenu: Fix a possible location mismatch

- src/styles/keymap.css
When sizing the keymap, adjust it to the actual screen sizes instead of doing guess-work.
This gets rid of the vertical scrollbar in most cases. It does set a minimum size, at which point scrollbars will appear. But until then, it's resizing nicely.
> Better keymap sizing

- src/renderer/App.js
- src/renderer/components/Header.js
We should only show a prompt when discarding unsaved changes, not when we're explicitly saving them. To achieve this, `App.cancelContext()` now takes a `dirty` argument, and only pops up the dialog when the flag is set. Cancelling the context will set the dirty flag, any other call-site will not.
In practice, this fixes #335.
> Do not ask for confirmation when saving

- src/renderer/App.js
- src/renderer/screens/KeyboardSelect.js
Do the Editor / Welcome routing in `onKeyboardConnect` instead of doing it in `KeyboardSelect`. This way we can avoid the `navigate(".")`, which screws up the reconnect on the Welcome screen.
Fixes #333.
> App: Do the Editor / Welcome routing in `onKeyboardConnect`

- src/renderer/screens/Editor.js
- src/renderer/screens/Editor/Palette.js
When we're on a negative layer, or a layer higher than the length of the colormap, don't touch the colormap.
Fixes #342.
This isn't perfect, the colormap editor controls aren't properly disabled - but they don't do anything in these cases, which is a bit better than crashing. Adding disabled support for those controls is a bit more involved, will do that in a separate PR at some point.
> Editor: Don't touch the colormap when we're out of bounds

- package.json
- src/renderer/screens/Editor.js
- yarn.lock
If we have no custom keymap, we should force onlyCustom off (this is done by the updated `@chrysalis-api/keymap` package). We should not copy the default layers to custom if custom was an empty array.
Together, these fix #336.
> Editor: Handle the corner case of no custom keymap better

- src/renderer/i18n/en.js
- src/renderer/i18n/hu.js
- src/renderer/screens/Editor.js
This is an initial approximation of the layer import/export feature, an MVP of sorts.
It's still a work in progress, with a few known issues:
> Editor: Initial layer export/import support

- src/renderer/App.js
- src/renderer/i18n/en.js
- src/renderer/i18n/hu.js
- src/renderer/screens/Preferences.js
- src/styles/darkTheme.js
- src/styles/lightTheme.js
Initial support for manual switching to the stock Material UI dark theme with preference being saved using electron-settings.
Signed-off-by: Tré Ammatuna <tre@tretuna.com>
> Initial Dark mode support

- src/renderer/screens/Editor.js
When deciding whether to set the colors, we wanted to avoid setting it for negative layers (ie, when using custom layers only, but having default layers shown, and being on a default layer). However, the comparison was done wrong, we compared `layer > 0` instead of `layer >= 0`. This fixes that, and setting colors on the base layer works again now.
Fixes #352.
> Editor: Fix editing the colormap on layer 0

- package.json
Small update to make the main toolbar change along with the dark mode setting in MacOS.
Notes:
Does not affect the current manual user setting in preferences for `Dark mode`.
Does not show in dev mode, only on the final build. This is due to the fact that this is just a setting in `electron-builder`
> Shade the main toolbar along with Mac preferences for Dark mode

- src/renderer/screens/Editor/ImportExportDialog.js
Since snack bars are set to never autohide by default right now we have to explicitly set these to do so.
Signed-off-by: Tré Ammatuna <tre@tretuna.com>
> Auto hide copy/paste snackbars after 2 seconds

- src/renderer/screens/Editor/Editor.js
As discussed in #385, this moves the layer dropdown to the right side, and changes the layer clear icon.
> Move the Layer dropdown, and change the layer clear icon

- src/renderer/screens/KeyboardSelect.js
When enumerating (USB Serial) devices, let the hardware plugins have more say in which variants of a device they support. By using the new `focus.isDeviceSupported()` method, they can do arbitrary checks and decide the device is not something they support, in which case it gets filtered out.
Depends on keyboardio/chrysalis-api#23, and is an alternative solution for #378.
> KeyboardSelect: Let hardware plugins have more control over enumeration

- src/renderer/components/ColorPalette/ColorButton.js
- src/renderer/components/ColorPalette/ColorButtonsArea.js
- src/renderer/components/ColorPalette/ColorPalette.js
- src/renderer/components/ColorPalette/PickerColorButton.js
- src/renderer/i18n/en.js
- src/renderer/screens/Editor/Editor.js
**Enhancements:**
1) bottom menu doesn't hidden after starting app, and after switching between `colored` and `keys` panels (depends to #396)
2) `button-Pallete` disabled in case `color-button` not on active stage
- to reproduce Multiple selection is just should activate (make a click) a `color-button` and than click to any keys you would like to change a color (except current key => cause it will hide the panel)
- to  turn off `color-button` - just click once again on it
- to know what the color is on current key - press `CTRL` and click the key - `color-button` turning on (as box-shadows around)
Also added a prevention for `color-button` - in case using `CTRL` and click to the `color-button` nothing will changes (its lock to prevent during clicking the key) …
> (#382) multiple select LEDs

- package.json
- src/renderer/i18n/en.js
- src/renderer/i18n/hu.js
- src/renderer/screens/Preferences.js
- yarn.lock
Add an option to toggle the verbose logging of the Focus package, to the advanced section of the preferences screen. This also updates the `@chrysalis-api` packages to their latest, to pull in a Focus with the required functionality.
> Preferences: Add a verbose logging option

- README.md
The existing markdown renders as a single line, which errors when pasted into a terminal:
```
$ brew update && brew upgrade brew cask install chrysalis
Already up-to-date.
Error: No available formula with the name "brew"
```
> Formatting for Homebrew commands

- package.json
- src/renderer/screens/Editor/KeySelector.js
- yarn.lock
This makes it possible to set up a key that becomes `AltGr` (or `Right Alt`) when held, and a normal key otherwise.
We need an update to the key database too, for proper display. I'll fix the `@chrysalis-api/keymap` library, and push an update to this PR after.
> Editor: Support AltGr as a DualUse modifier

- src/renderer/i18n/en.js
- src/renderer/screens/KeyboardSettings.js
This adds a little slider to the Keyboard Settings menu, but only when connected to a keyboard with support for it exposed:
> KeyboardSettings: Add brightness controls

- package.json
- src/renderer/index.js
- src/renderer/screens/FirmwareUpdate.js
- yarn.lock
Upgrade the `notistack` dependency, so we have a version with which we can do dismissability the way we want. Also update the default notification buttons to take advantage of this, and teach the error notification from flashing to have a dismiss button aswell.
Fixes #446.
> Fix notification dismissability

- src/renderer/i18n/en.js
- src/renderer/screens/Preferences/KeyboardSettings.js
This implements an idle time limit control widget for the Keyboard Settings screen, on connected boards that support it.
Because it touches the same code as #456, to avoid conflicts, this is based on top of that PR. If need be, I can rebase it onto master.
> KeyboardSettings: Idle time limit control

- README.md
OS X 10.11 (El Capitan) was released in 2015, all subsequent versions of "OS X" was renamed to MacOS starting with macOS 10.12 (Sierra) released 20. september 2016. 
This pull request only changes all instances of OS X in the README.md at root level of this project to "MacOS"
> Change from OSX to MacOS in Readme

- package.json
- src/main/dragons.js
- src/main/index.js
- yarn.lock
Due to electron-userland/electron-webpack#275, we need to set `NODE_ENV` in the main process, as early as possible, to the correct value. We also need to do that in a strange, perhaps a bit ugly and verbose way, to avoid webpack optimizing important parts of it out.
With this workaround, we can use the latest webpack, without serial operations getting stalled.
Thanks to @obra for hunting down the problem, and pointing me to the webpack issue above!
As such, this also updates `electron-webpack` to a more recent version, now that we can.
> Set `NODE_ENV` correctly in the main process

- README.md
Signed-off-by: Jesse Vincent <jesse@keyboard.io>
> Apple styles their operating system for Macs as 'macOS', not 'MacOS'

- src/renderer/i18n/en.js
- src/renderer/i18n/hu.js
- src/renderer/screens/Editor/Editor.js
If the connected keyboard has a zero-length palette, do not display the layout/colormap switch button, and only mention "Layout Editor" in the title.
Fixes #477.
> Only display the colormap editor switch if colormap is supported

- src/renderer/i18n/en.js
- src/renderer/i18n/hu.js
- src/renderer/screens/FirmwareUpdate.js
- src/renderer/screens/Preferences/KeyboardSettings.js
- src/renderer/utils/clearEEPROM.js
While we can reset the EEPROM post-flash, it's easier if we can do both at once.
> Add an option to restore factory defaults during flashing

- src/renderer/App.js
- src/renderer/i18n/en.js
- src/renderer/i18n/hu.js
- src/renderer/screens/Editor/Editor.js
The Editor screen already had support for cases where we only have a keymap, but no colormap; it also supported having both; but it lacked support for the case where we only have a colormap.
There are many valid reasons for not having an editable keymap, and not having the `EEPROMKeymap` plugin enabled at all. This patch reworks the Editor screen a bit so that we support firmware with said plugin disabled, too.
Fixes #496.
> Editor: Support cases where we have a colormap only

- src/api/keymap/db/miscellaneous.js
Adds a label and keycode for the Num Lock key.
I've validated the keycode using the "Unknown keycodes" entry in Chrysalis and confirmed it sends the correct Num Lock code on Windows 10.
> Add Num Lock key

- src/api/keymap/db/miscellaneous.js
- src/api/keymap/db/modifiers.js
- src/api/keymap/db/punctuation.js
Move Caps Lock, Scroll Lock, and Num Lock to the modifiers group, and rename it to "Modifiers & Locks".
> keymap: Move the various *Lock keys to modifiers

- src/api/flash/index.js
- src/api/hardware-keyboardio-atreus2/index.js
- src/api/hardware-keyboardio-model01/index.js
- src/renderer/i18n/en.js
- src/renderer/i18n/hu.js
- src/renderer/screens/FirmwareUpdate.js
Knowing what's happening, what we're waiting for, is very valuable information, both for the user, and for developers too, when working on bug reports. To this end, lets display a progress bar when flashing is in progress, giving a rough outline about where we are in the process.
At the moment, this is only implemented for boards using the Avr109 flashing protocol. The others will display a progress stepper too, but with a single element only, for now.
Fixes #492.
The progress bar is not shown until the "Update" button is pressed:
Without the factory reset option set, we start by triggering the bootloader, and then waiting for it:
And finally, we flash:
---
With the factory reset enabled, we have an additional step in the beginning:
> Add a progress bar to the FirmwareUpdate screen

- src/api/focus/index.js
- src/renderer/i18n/en.js
- src/renderer/screens/KeyboardSelect.js
On Linux, before allowing to connect to a keyboard, check that the device file has read and write permissions. If it is not, disable the connect button, and display an error.
Fixes #500.
> KeyboardSelect: Check device permissions on Linux

- build/afterPackHook.js
- build/launcher.sh
- package.json
On Linux, sandboxing requires either a suid root helper (which we can't ship in the AppImage build), running as root (which is something we'd rather avoid), or unprivileged user namespace cloning (which is only available on more recent kernels). Since we do not want to run as root, and we'd like users to run Chrysalis without having to explicitly pass arguments to it, on Linux, we wrap the launcher.
The wrapper checks for the necessary kernel feature, and disables the sandbox if the feature is not available. This is still a better and safer experience than running as root, or than the user having to explicitly run Chrysalis with `--no-sandbox`.
This is only done on Linux, and only for the AppImage build. Running `yarn run start` will still require the extra flag.
> Optionally disable the sandbox on the AppImage build

- .gitignore
Adds lines to gitignore that will ignore workspace configuration folders for vscode and jetbrains IDEs.
See: 
https://rider-support.jetbrains.com/hc/en-us/articles/207097529-What-is-the-idea-folder-
https://code.visualstudio.com/docs/getstarted/settings
These are fairly common IDEs and it will help keep future commits and contributions clean.
> Add Jetbrains and VSCode workspace config folders to .gitignore

- package.json
When we added the special launcher for older Linux distributions, we overrode `build.extraResources` to include the launcher. However, said setting's default was to include the `static/` directory in the production builds.
This adds `static` back explicitly, so our production builds will have its contents bundled with them again.
> Do include the contents of static/ in production builds

- src/api/flash/index.js
- src/api/focus/index.js
- src/renderer/components/ConfirmationDialog.js
These fixes improve the flashing process in various ways:
- When asking for confirmation (such as when we're about to restore factory settings during flashing) the dialogs will now ignore the `Esc` key, so when we hold it to enter bootloader mode, we no longer cancel the process.
- The error handling in the Avr109 flasher was substantially improved: we no longer pollute the developer console with errors unless there really is one. In other words, we only try to close the serialport if it is open, and we try to catch more errors from AvrGirl, to report them accurately instead of ending up with an uncaught exception.
> Flashing process fixes

- src/renderer/App.js
If we have pending, unsaved actions, we put the AppBar in context mode. However, when the keyboard physically disconnects, we can no longer do anything about these unsaved actions. As such, lets put the AppBar back in normal mode, and cancel the context.
Fixes #393.
> Cancel the context state of the AppBar when a keyboard disconnects

- src/renderer/components/Header.js
In Dark mode, the header text was not changing colors. It appears that this was due to the `color: inherit` property being set. Removing this, the header text now respects the theme color.
light
dark
light
dark
---
Issue : #471
> Bug: In dark mode, header text should be white

- src/renderer/screens/Editor/Editor.js
- src/renderer/screens/Editor/KeySelector.js
When a user selects a key that would change layers or otherwise be bound to a layer, they are presented with a list that may not represent the layers available to their keyboard. This PR adds in a check to see if the keygroup being displayed represents layers, and then limits the layers shown to that available to the keyboard.
Currently, I applied this to the shiftTo, lockTo, and oneShotLayer keygroups (9,10,19). I am unsure if there are other layers that should be included.
with layers limited
1. Plug in a keyboard
2. Visit the editor page
3. Select a modified keygroup in the keyselector (shift to layer, lock to layer, oneshot layer)
4. observe that the number of layers displayed is representative of the keyboard layers.
---
Issue: #473
> Feature: Limit layer key bindings to layers available

- src/renderer/screens/Editor/Editor.js
1. connect a keyboard with no colormap / no colormap set (atreus2 worked for me)
2. In the editor screen, attempt to clear any layer.
> Clearing a layer causes Chrysalis to crash if there is no color map

- src/renderer/screens/Editor/Editor.js
1. Open export/import on an atreus 2 or keyboard with no colormap.
2. modify anything
3. click ok
1. Import a layer with no colormap. Here is the default layer 0 from the atreus2 (this is what was exported by Chrysalis):
```json
{
"keymap": [
{
"keyCode": 20,
"label": "Q"
},
{
"keyCode": 26,
"label": "W"
},
{
"keyCode": 8,
"label": "E"
},
{
"keyCode": 21,
"label": "R"
},
{
"keyCode": 23,
"label": "T"
},
{
"keyCode": 0,
"label": "Blocked",
"verbose": "Disabled"
},
{
"keyCode": 0,
"label": "Blocked",
"verbose": "Disabled"
},
{
"keyCode": 28,
"label": "Y"
},
{
"keyCode": 24,
"label": "U"
},
{
"keyCode": 12,
"label": "I"
},
{
"keyCode": 18,
"label": "O"
},
{
"keyCode": 19,
"label": "P"
},
{
"keyCode": 4,
"label": "A"
},
{
"keyCode": 22,
"label": "S"
},
{
"keyCode": 7,
"label": "D"
},
{ …
```
> Fixes: Crashes on import if colormap property is not present

- src/renderer/i18n/en.js
Just a small fix for a classic UI issue.
Basically, it's asking "do you want to cancel these changes?" which makes the "Cancel" button ambiguous (will it cancel the changes, or cancel the cancel?)
Just changes the dialog title to "Discard pending changes?" for which the "OK" and "Cancel" options are less confusing.
> Change "cancel" to "discard" to avoid ambiguity

- build/launcher.sh
If `/proc/sys/kernel/unprivileged_userns_clone` does not exist, do not fail and exit immediately, but assume that the feature is not available.
This should fix the app being unable to start on Fedora32.
> build/launcher.sh: If the file in /proc does not exist, treat it as no support

- static/Keyboardio/Atreus/colemak.json
- static/Keyboardio/Atreus/dvorak.json
- static/Keyboardio/Atreus/qwerty.json
Fixes #527.
Alternative keyboard layouts are available for the Model 01.
They are not currently available for the Atreus.
This commit adds the keyboard layouts for the Atreus.
Specifically, it adds:
1. Colemak
2. Dvorak
3. Qwerty
These are now available from the Import/Export page for the Atreus.
I hope I got the `/` and the `-` keys in the right place for the Dvorak layout, but please double check that.
> Add keyboard layouts for the Atreus

- src/api/hardware-keyboardio-model01/index.js
so we can expire old links to combat spam.
> Set our discord link to a redirect

- src/api/keymap/db/modifiers.js
Currently the "Modifiers & Locks" keymap has "LEFT ALT" and "ALTGR"
This PR updates the UI to add Right Alt in parens next to AltGr, for those who are unsure of what is AltGr.
> Add "Right Alt" in parens to AltGr

- src/renderer/components/LoadingScreen.css
- src/renderer/components/LoadingScreen.js
- src/renderer/config.js
- src/renderer/i18n/en.js
- src/renderer/i18n/hu.js
- src/renderer/screens/Editor/Editor.js
When communicating with the keyboard, and we expect that it might take a while, try showing a loading animation instead of just a partial render. This should result in a considerably nicer user experience.
The component is currently only used by the Editor screen, but we may want to use it elsewhere too.
The logo is animated, and is spinning slowly.
> Add a LoadingScreen component

- src/renderer/App.js
- src/renderer/screens/KeyboardSelect.js
These patches do a number of things, that I hope, will improve both the automatic keyboard scanning system, and the way we handle connected keyboards detaching.
First of all, we no longer scan for new keyboards _immediately_ when we receive an USB attach or detach event: we merely take a note that said event happend. Then, every 10 seconds or so, we do the automatic scan, but only if we had an event since the last scan attempt. The aim of this is to reduce the spammyness of scanning, and to give time for the attached hardware to settle.
Secondly, when handling the detachment of a connected keyboard, we _always_ navigate to the keyboard selection screen at the end of the handler, not only when the port was half-closed. On some operating systems, we may get a detach event sooner than the …
> Keyboard scanning and disconnecting improvements

- src/renderer/components/MainMenu/MainMenu.js
When we upgraded to Material UI 4, link colors in the main menu turned from dark grey to blue. That wasn't intended, so this little change restores the proper color of the links.
Bug:
Fix:
> components/MainMenu: Fix the link colors

- .travis.yml
- README.md
- tools/get-artifact
- tools/s3-upload.js
Travis has a Linux/arm64 environment, Chrysalis builds there fine, and works well on arm64, too. As such, adjust our Travis config to build it, and the artifact upload/download tools to support multiple architectures for Linux.
Fixes #524.
For build logs, see [here](https://travis-ci.org/github/keyboardio/Chrysalis/builds/734290991).
> Add support for Linux/arm64 builds

- .github/ISSUE_TEMPLATE/bug_report.md
Now that we have a "System Information" screen that can create debug bundles, suggest that screen in the template, instead of recommending saving the dev console contents.
> github: Update the bug report template

- src/renderer/i18n/en.js
- src/renderer/i18n/hu.js
- src/renderer/screens/Editor/Editor.js
When we're warning the user about using mixed hardcoded & custom layers, instead of directing them to open a feature request in text, provide a button instead.
> Editor: Add an "Open Feature Request" button to the onlyCustom warning

- src/api/keymap/chrysalis-keymap.js
- src/api/keymap/db.js
- src/renderer/screens/Editor/Editor.js
- src/renderer/screens/Editor/ImportExportDialog/ImportExportDialog.js
This is a bare minimum pass at implementing #562. The format is pretty verbose, but should be easy to iterate on later since it includes a version tag. Also, expanding `db.parse` and `db.serialize` should allow for reworking the representation of keys in a backwards compatible way.
Starting as a draft since I think it still needs some testing (don't have a keyboard with colormap support handy) as well as some discussion on the serialization format. Also have some placeholder code in db based on discussions about some upcoming changes, but these need to be discussed as well.
Current format looks like this:
```js
{
"configVersion": 1,
"device": {
"vendor": "Keyboardio",
"product": "Atreus",
"displayName": "Keyboardio Atreus",
"urls": [{"name": "Homepage", "url": …
```
> First pass at exporting full layouts

- .eslintrc.js
- src/renderer/components/LoadingScreen.js
- src/renderer/components/MainMenu/MainMenu.js
- src/renderer/i18n/en.js
- src/renderer/i18n/hu.js
- src/renderer/screens/SystemInfo.js
This PR adds `plugin:jsx-a11y/recommended` to eslint settings and fixes all pre-existing violations.
The violations fall into 2 categories:
* `<img>` elements representing the Chrysalis logo with no alt text. These were fixed by adding alt text "Chrysalis logo"
* A `role="button"` element in `MainMenu` which did not appear in tab order. This element was an invisible wrapper around all the menu items which gets "clicked" via fall-through when a menu item is clicked (or when a particular subset of the empty space in the menu was clicked) which dismissed the menu. I removed this element entirely and instead added `closeMenu` calls to the handlers for the menu items; this results in a flatter DOM structure and avoids closing the menu when clicking on the empty parts of its top.
Note that …
> Enable eslint plugin:jsx-a11y/recommended and fix existing violations

- src/api/focus/index.js
This documents why we have the workaround for writes in `api/focus` on macOS: because without splitting the data into smaller chunks, we seem to overwhelm the system, and the host will receive garbage. Also noted a possible improvement there.
~~This removes the macOS-specific workarounds from `api/focus`, which should speed up Chrysalis on mac considerably.~~
~~I'm setting this as a draft, because we had a reason for the workaround, which, I believe, we fixed, and it WorksForMe™, but I'm not 100% sure what the cause of the original problem was, and as such, I'm not certain that the fix we have (ie, setting `clocal` on the serial port) is enough.~~
> api/focus: Document the macOS workaround

- package.json
- src/api/keymap/cldr.js
- src/api/keymap/db.js
- src/api/keymap/db/us/qwerty.js
- src/renderer/screens/Editor/Sidebar/KeyPicker.js
- src/renderer/screens/Editor/Sidebar/KeyPicker/LayoutSelect.js
- yarn.lock
There are three major things done here: first, the layout selector was changed from a simple dropdown to an autocomplete-able input. Second, we now load _all_ layouts from CLDR, and third, we group them by language.
The result is, in my opinion, quite pleasing:
Turning the selector into an autocomplete-able input also has the advantage that when one starts to type in it, it takes the whole typed string into account.
Fixes #633.
> Editor: Improve the host layout selector

- src/api/hardware-keyboardio-atreus2/components/Keymap.js
Fixes #669.
There was a regression when the new UI code was implemented and a piece of
code that applied conditional formatting went missing.
Signed-off-by: RodrigoRoaRodriguez <rodrigoroarod@gmail.com>
> [Fix regression] Larger  key legends for single characters

- src/renderer/screens/Editor/Sidebar/Overview/LayoutSharing.js
When saving the keyboard layout to a file, having a default filename is
friendlier than nothing, and it's even better with the json extension.
resolve #663
Signed-off-by: Romain Heller <Rom1deTroyes@users.noreply.github.com>
> ~[Export Layers] Add a default name to the exported file

- src/renderer/i18n/en.js
- src/renderer/screens/Editor/Editor.js
- src/renderer/screens/Editor/components/OnlyCustomScreen.js
Chrysalis no longer supports mixing hardcoded and custom layers, because they were confusing. However, showing an alert below the toolbar, but otherwise letting the user to continue also led to surprising behaviour, such as disabling the keyboard in some cases when pressing the "Fix it" button.
To combat these issues, these changes turn the alert into a separate screen, where the case, and the suggested solution is better explained. This prevents the user from editing the keymap and wondering why it doesn't work the way it should, and the "fix it" button is better explained too (and renamed, to `Switch to custom layers only`).
Additionally, when Chrysalis decides to copy the default layers to eeprom, it will also tell the keyboard to use custom layers only. This way, anyone plugging in a …
> Show a prompt screen instead of an alert when encountering mixed layers

- build/launcher.sh
- package.json
- yarn.lock
This upgrades Electron to v12 (which ships with a Chromium that has initial support for Wayland), and adjusts the AppImage launcher script so that if wayland is detected, it will let Electron know we want to use it.
Fixes #668.
> Initial support for Wayland on Linux

- src/api/keymap/chrysalis-keymap.js
- src/api/keymap/db.js
- src/api/keymap/db/base/consumer.js
- src/renderer/i18n/en.js
- src/renderer/screens/Editor/Editor.js
This implements a check on the Editor screen, that displays a warning when we find a keymap with legacy keycodes on it, and offer to migrate to new ones. Right now, the only such keycodes are the old Consumer Control keys (see #680, #677, and #678), but the migration code is generic, and it's trivial to migrate any keycode: all we need is a `legacyCode` property on the key, and Chrysalis will do the right thing.
Migrating does _not_ save the result to the keyboard, to allow users to review any changes, and make sure they're correct.
The warning looks like this:
And after migration:
> Editor: Legacy code migration

- src/api/keymap/db/base/spacecadet.js
The keycode values for the SpaceCadet enable and disable keys were off by one, such that the "disable" key was actually the _enable_ key, and the "enable" key was in the Steno range.
Fixes #697
> Fix SpaceCadet enable and disable key values

- src/renderer/i18n/en.js
Just a minor double word cleanup on a tooltip in the english translation file.
> Remove duplicate 'modifier' word in OneShot sticky tooltip

- src/renderer/i18n/en.js
To make it clearer that the key needing to be held is tied to a position, not to a mapping, reword the update instructions to mention the position first, and the mapping as a comment. Also clarify that the mapping mentioned is according to the default layout.
Fixes #701.
> flashing: Clarify the flashing instructions for Keyboardio devices

- src/renderer/i18n/en.js
Changes "hulding" to "holding" in the flashing instructions for the Model01.
> Typo in Model01 Flashing Instructions

- src/api/keymap/db/base/oneshot.js
- src/renderer/i18n/en.js
- src/renderer/screens/Editor/Sidebar.js
- src/renderer/screens/Editor/Sidebar/OneShotKeys.js
This depends on keyboardio/Kaleidoscope#1089, and adds support for both the dedicated one-shot cancel key, and for toggling the functionality on and off to begin with.
I feel the wording of the help text, and the labels could be improved, help on that would be most appreciated.
> Add support for Escape Oneshot

- electron-webpack.json
- package.json
- src/renderer/App.js
- src/renderer/components/MainMenu/ChangeLogMenuItem.js
- src/renderer/components/MainMenu/MainMenu.js
- src/renderer/i18n/en.js
- src/renderer/screens/ChangeLog.js
- yarn.lock
One of the often requested features is to include the changelog in Chrysalis itself, so when one updates, they can quickly check what changed.
An initial implementation of that is hereby provided. It's not perfect, but it gets the job done:
Further improvements would be to collapse older entries, and only expand the most recent one by default.
> Add a Changelog screen

- src/renderer/i18n/en.js
that's what the feature really is right now.
Longer term, this should become it's own screen in the main menu. But this is ok for the moment.
> Rename layout sharing to 'Backup and Restore'

- src/main/index.js
- src/renderer/App.js
- src/renderer/screens/KeyboardSelect.js
USB hotplug detection runs in the main process.
We no longer notify that we should poll after a timeout. Instead we notify that we should poll now. It simplifies the code and improves the UX.
It also no longer causes Electron to randomly segfault on macOS
> Switch how we do USB hotplug notifications to the "new" WebUSB way.

- src/main/index.js
- src/renderer/index.js
We were missing the mandatory configuration for hot module reload to work in dev
Signed-off-by: Jesse Vincent <jesse@keyboard.io>
> Enable hot module reload, dramatically improving developer UX

- src/api/focus/index.js
This PR changes the logic of how we speak focus to darwin devices. After these changes, I've stopped being able to make Chrysalis fail to talk to an Atreus from a mac, something that was otherwise a regular occurrence.
> Our macos 'delay' logic was badly flawed. 

- src/renderer/App.js
- src/renderer/screens/Preferences/Basic.js
use a BrowserChannel to do in-renderer IPC. This helps make different
bits of code a bit more independent.
Also, now change the preference from within the prefs screen, rather
than over in the apps screen
> Rather than needing to pass accessor and mutator for darkmode around,

- src/renderer/App.js
- src/renderer/components/ContextBar.js
- src/renderer/components/Header.js
- src/renderer/screens/Editor/Editor.js
- src/renderer/screens/Preferences.js
- src/renderer/screens/Preferences/KeyboardSettings.js
I'm not thrilled with this implementation, but I believe it to be better encapsulated than what we had before. I think we ought to be able to use global state to do the exact same thing, but nicer and simpler. But one step at a time.
> Rename and simplify the context bar undo manager just a little bit.

- src/renderer/screens/KeyboardSelect.js
When there's only one keyboard detected, attempt to auto-connect. We only do this when the component mounts and we aren't already connected.
If there are multiple devices, or if we're connected already, or we disconnect from the same screen, we will not auto-connect.
Fixes #595.
> KeyboardSelect: When there's only one keyboard present, auto-connect

- src/api/flash/index.js
- src/main/ipc_backups.js
- src/renderer/screens/Editor/Sidebar/Overview/LayoutSharing.js
We do not want to offer backups made from a Model01 when on an Atreus. To this end, save backups in a vendor/product subdir, and load the library from that directory too.
While there, renamed the IPC functions to be more consistent, too.
Fixes #804, and also fixes #806.
> backups: Make automatic EEPROM backups device-type specific

- src/api/focus/index.js
- src/renderer/ActiveDevice.js
Upon `probe()`, save the results of  `help`, so we have a list of commands. Clear it on `close()`. We'll use this list of supported commands in `request()` to see if the requested command is supported, and if it isn't, we simply return no data, without sending the request.
This reduces traffic between keyboard and host, and fixes #802.
> api/focus: Do not send unknown requests

- src/renderer/i18n/en.js
- src/renderer/screens/FirmwareUpdate.js
When we reach the waiting-for-bootloader step of the firmware flashing process, it is safe to release the PROG key (or its equivalent). Pop up a toast letting the user know.
We do this when we start to wait for the bootloader, rather than after, to give enough time for the user to react. If we do it at the start of `flash` (the usual next step), we only have a couple of seconds to react before flashing finishes. Doing it at this time gives us a few more.
> FirmwareUpdate: Let the user know when they can release PROG

- src/renderer/screens/Editor/Sidebar.js
Our last Collapsible hitting the very border of a window looked a bit awkward. Adding a small margin makes it look nicer.
Fixes #823.
> Editor/SideBar: Add a small margin at the bottom

- src/renderer/screens/FirmwareUpdate.js
The major part of this pull request is fixing #811, which looked very weird, out of place, and not very professional, to say the least.
We do this by caching the available flash steps on mount, so that they don't accidentally become unavailable during a reboot or reconnect operation. This way we avoid the default "flash" step kicking in.
On top of that, once we're done flashing, successfully, we mark the last step as completed before returning to the keyboard selection screen.
And as an extra improvement, after a successful flash, the success notification no longer stays up indefinitely, but closes automatically after 10 seconds. The idea behind this is that after a flash, the user may likely want to connect to the keyboard - or might even get automatically reconnected -, and in that case …
> Assorted Firmware Upgrade UX fixes

- src/renderer/ActiveDevice.js
- src/renderer/screens/KeyboardSelect.js
When we arrive on the KeyboardSelect screen, we want to show the currently active device as the initially selected device. To do that, we perform an initial scan, and iterate through the device list returned to see if we're connected to any of them. If we are, we simply set the selected port index accordingly. We do this only once per mount.
The periodic device scans have been changed from `useIntervalImmediate` to `userInterval`, because we handle the initial scan via `useEffectOnce`, which does the scanning too.
Fixes #809.
Signed-off-by: Gergely Nagy <algernon@keyboard.io>
> KeyboardSelect: Pre-select the active device (if any)

- src/renderer/i18n/en.js
- src/renderer/screens/LayoutCard.js
- src/renderer/screens/Preferences/UserInterface.js
If we're connected to a keyboard that has Colormap support, render the layers with the colormap applied, too.
> LayoutCard: Use the colormap too when rendering, if available

- src/api/focus/index.js
- src/renderer/ActiveDevice.js
- src/renderer/hooks/usePluginVisibility.js
- src/renderer/i18n/en.js
- src/renderer/screens/Editor/Sidebar/LayerKeys.js
- src/renderer/screens/Editor/Sidebar/LeaderKeys.js
- src/renderer/screens/Editor/Sidebar/MacroKeys.js
- src/renderer/screens/Editor/Sidebar/Modifiers.js
- src/renderer/screens/Editor/Sidebar/MouseKeys.js
- src/renderer/screens/Editor/Sidebar/OneShotKeys.js
- src/renderer/screens/Editor/Sidebar/SecondaryFunction.js
- src/renderer/screens/Editor/Sidebar/SpaceCadetKeys.js
- src/renderer/screens/Editor/Sidebar/StenoKeys.js
- src/renderer/screens/Editor/Sidebar/TapDanceKeys.js
- src/renderer/screens/Preferences/UserInterface.js
Recent firmware supports a `plugins` command, letting us query the list of available plugins. We can leverage this information to hide functionality from the sidebar for which firmware-side support does not exist - at least optionally. This pull request does just that.
The parts of the Sidebar which depend on firmware-side plugins will now check if they should make those functions visible. They do so via the new `usePluginVisibility()` hook that checks the available plugin list, and also consults the UI settings, which can override the default hiding behaviour.
The result is a considerably cleaner sidebar, with no fluff. With hiding functionality not supported by the firmware, we avoid surprises: a very frequently asked question on Discord is why "Secondary actions" don't work, and the …
> Teach the sidebar to hide unavailable functionality by default

- package.json
- yarn.lock
This is the latest in the 17.x series, and fixes a few Wayland-related issues people were having. Might even render --disable-gpu obsolete, but lets try with that still in use first.
> Bump our Electron dependency to 17.4.6

- package.json
- yarn.lock
There are no documented breaking changes in v18 or v19 that apply to us.
> Upgrade to Electron 19, the current production release.

- src/renderer/screens/Editor/Macros/MacroEditor.js
When mounting the editor, listen for keydown events (and remove them on cleanup), and if we encounter an `Escape` keypress, close the editor. This makes it behave a bit like a dialog.
Fixes #858.
> MacroEditor: Close the editor when pressing Escape

- src/renderer/screens/Editor/Editor.js
The macro editor depends on having macro support, so we should not try to open it when we do not support dynamic macros. We can't guard against it within the Macro Editor itself, because the best we can do there is not render - but the Editor will still consider us open then.
So if our macro storage space is zero (either DynamicMacros is not enabled, or not configured), we simply don't open the editor.
This fixes an exception when trying to assign a dynamic macro to a key on keyboards that do not support them. Assigning a dynamic macro always tried to open the editor before, and thus, bombed out. Now we assign the key, but don't try to open the editor, and all is well.
> Editor: Prevent opening the macro editor if we don't support macros

- src/renderer/i18n/en.js
The instructions were originally copied from the Model 01, but there are two subtle changes for the Model 100: the LEDs are lit up green instead of red, and they're restricted to the first column.
Fixes #850.
> Model100: Adjust the firmware update instructions

- src/main/index.js
- src/main/ipc_nativetheme.js
- src/renderer/App.js
- src/renderer/components/GlobalContext.js
- src/renderer/i18n/en.js
- src/renderer/screens/Preferences/ui/LookAndFeelPreferences.js
- src/renderer/utils/darkMode.js
Instead of having a toggle between light and dark mode, support arbitrary themes by storing the theme name in a setting, rather than a dark mode toggle.
This allows us to have a "system" theme (along with "light" and "dark"), which follows the system theme on operating systems that have one (macOS & Windows).
The old `ui.darkMode` setting is honored, and will be migrated automatically to the new setting. For new users, we default to the system theme.
Fixes #874.
> Improve our theme system

- src/renderer/screens/Editor/Editor.js
- src/renderer/screens/Editor/Sidebar.js
- src/renderer/screens/Editor/Sidebar/Colormap.js
- src/renderer/screens/Editor/Sidebar/Overview.js
- src/renderer/screens/Editor/Sidebar/SecondaryFunction.js
- src/renderer/screens/Editor/Sidebar/StenoKeys.js
- src/renderer/screens/Editor/Sidebar/TapDanceKeys.js
Certain elements of the sidebar do not make sense in the context of the macro editor, so hide them to reduce unnecessary clutter, and avoid confusion.
The hidden parts are:
- The overview, because switching layers during macro editing is a strange and confusing experience.
- The colormap section, because that's irrelevant in context of the macro editor.
- Steno and TapDance keys, for the same reason.
- The Secondary Function section, likewise.
Fixes #867.
> Editor: Hide parts of the sidebar when the macro editor is open

- src/renderer/i18n/en.js
- src/renderer/screens/Editor/Sidebar/OneShotKeys.js
- src/renderer/screens/Preferences/MyKeyboard.js
- src/renderer/screens/Preferences/keyboard/PluginPreferences.js
- src/renderer/screens/Preferences/keyboard/plugins/EscapeOneShot.js
Instead of having the EscapeOneShot cancel key configuration on the sidebar, move it to the Preferences screen, under My Keyboard.
As it doesn't fit any of the existing sub-sections, a new one ("Plugin preferences") was created for it.
Fixes #866.
> Preferences: Move the EscapeOneShot preferences here

- package.json
- yarn.lock
This is largely experimental, I only tested things a little, but it still appears to function.
We basically update a few packages we transitively pull in, usually in such a way that there's no other, clear upgrade path apart from adjusting resolutions. Most of these updated packages are not in use either directly or indirectly, and the one that is, appears to function properly still.
The reason for the upgrades is dependabot nagging us to do so, but it not being able to do it automatically, for the aforementioned reasons.
> Update a few package resolutions to make dependabot happy

- src/renderer/screens/Editor/Sidebar/Colormap.js
We used to override the width of the picker, but that no longer works, so wrap it in a Box and justify it to the center instead.
> Editor: Justify the color picker on the sidebar to the center

- package.json
- src/api/focus.js
- src/renderer/App.js
- src/renderer/hooks/useCheckDeviceSupportsPlugins.js
- src/renderer/hooks/usePluginCheck.js
- src/renderer/hooks/usePluginEffect.js
- src/renderer/i18n/en.js
- src/renderer/screens/Preferences.js
- src/renderer/screens/Preferences/Devtools.js
- src/renderer/screens/Preferences/MyKeyboard.js
- src/renderer/screens/Preferences/components/PreferenceSection.js
- src/renderer/screens/Preferences/components/PreferenceSwitch.js
- src/renderer/screens/Preferences/components/PreferenceWithHeading.js
- src/renderer/screens/Preferences/keyboard/AdvancedKeyboardPreferences.js
- src/renderer/screens/Preferences/keyboard/KeyboardLEDPreferences.js
- src/renderer/screens/Preferences/keyboard/KeyboardLayerPreferences.js
- src/renderer/screens/Preferences/keyboard/PluginPreferences.js
- src/renderer/screens/Preferences/keyboard/leds/Brightness.js
- src/renderer/screens/Preferences/keyboard/leds/DefaultLedMode.js
- src/renderer/screens/Preferences/keyboard/leds/IdleTimeLimit.js
- src/renderer/screens/Preferences/keyboard/plugins/EscapeOneShot.js
- src/renderer/screens/Preferences/ui/LayoutCardsPreferences.js
- src/renderer/screens/Preferences/ui/LayoutEditorPreferences.js
- src/renderer/screens/Preferences/ui/LookAndFeelPreferences.js
- src/renderer/screens/Preferences/utils/dividePreferences.js
- src/styles/keymap.css
- yarn.lock
Inspired by a combination of great suggestions given in [#880](https://github.com/keyboardio/Chrysalis/issues/880#issuecomment-1142443368), and [review notes](https://github.com/keyboardio/Chrysalis/pull/879#discussion_r885951725) in [#879](https://github.com/keyboardio/Chrysalis/pull/879#issuecomment-1142458353), I had another pass on the Preferences screen, and everything beneath.
The visible results are best explained in a video, just below. For demonstration purposes, all communication between keyboard and host had a two second delay added. Under normal circumstances, things are much, much more snappy - but I wanted to show how Skeletons appear during load.
https://user-images.githubusercontent.com/17243/171470122-7dc43ec8-5b90-4e15-820d-57667d46fe50.mp4
Under the hood, lots of …
> Another huge set of Preferences changes: both visible and code quality

- src/api/focus/keymap/db.js
- src/api/focus/keymap/db/constants.js
- src/renderer/screens/Editor/Editor.js
- src/renderer/screens/Editor/Sidebar/Modifiers.js
- src/renderer/screens/Editor/Sidebar/OneShotKeys.js
- src/renderer/screens/Editor/Sidebar/Overview.js
- src/renderer/screens/Editor/Sidebar/SecondaryFunction.js
- src/renderer/screens/LayoutCard.js
- src/renderer/screens/Preferences/keyboard/plugins/EscapeOneShot.js
There are a number of places in our code where we need to know the keycode of a particular key. Our keymap database isn't set up for easy queries that'd let us find these codes, and getting there would be complicated, so instead of doing that, I extracted the codes and ranges we used into `db.constants`.
This is a curated list of keycodes Chrysalis needs, and isn't a general purpose list.
All places that were using keycodes directly, either as keycodes, or as part of checking whether a key falls within a range, have been updated to use the new constants table instead.
It still has a bit of duplication, because the constants and the database must be in sync, but as our keycodes are static, this little duplication - a well contained one - is acceptable.
Fixes #877.
> api/focus: Add constants to our keymap database

- src/renderer/components/SaveChangesButton.js
- src/renderer/screens/Editor/Editor.js
- src/renderer/screens/FirmwareUpdate.js
- src/renderer/screens/Preferences/MyKeyboard.js
SaveChangesButton was suffering from various UX issues, such as not supporting dark mode in disabled state, and reacting to hover events separately for the circular and the regular part of it (in non-floating mode). The only use of it in non-floating mode was FirmwareUpdate, which this patch changes to use a regular Button, but still conveying similar information.
We originally used `SaveChangesButton` there because we had no other feedback about the progress of the flashing process. We have a Stepper now that adequately fulfills that role, so we no longer need the feedback on the button.
With the only user of non-floating `SaveChangesButton` gone, we can simplify it greatly by removing the text part and all the workarounds that came with it. This restores dark mode support to the button, …
> FirmwareUpdate: Use a regular button with an icon, instead of SaveChangesButton

- src/renderer/screens/Editor/Editor.js
During `scanKeyboard()`, look at `settings.defaultLayer` too, and if it has a sensible value, set the current layer to that.
Fixes #610.
> Editor: Switch to the default layer, if any

- .github/workflows/lint.yml
It happend a few times before that we updated `package.json`, but forgot to update `yarn.lock`. This extra steps make sure we don't miss that.
> CI: Check if yarn.lock is up to date as part of the lint workflow

- src/renderer/App.js
For LayoutCard to be able to handle errors properly, it needs the `onDisconnect` handler. Pass it along.
Fixes #896.
> App: Set the onDisconnect property on LayoutCard

- src/api/focus.js
- src/main/index.js
- src/main/ipc_device_discovery.js
- src/main/ipc_devtools.js
- src/main/ipc_file_io.js
- src/main/ipc_nativetheme.js
- src/renderer/App.js
- src/renderer/Error.js
- src/renderer/components/GlobalContext.js
- src/renderer/i18n/en.js
- src/renderer/index.js
- src/renderer/screens/Editor/Sidebar/LayoutSharing/ExportToFile.js
- src/renderer/screens/FirmwareUpdate.js
- src/renderer/screens/KeyboardSelect.js
- src/renderer/screens/Preferences/Devtools.js
- src/renderer/screens/SystemInfo.js
- src/renderer/utils/findKeyboards.js
This harmonizes our IPC call naming, so everything follows the same pattern.
As an additional benefit, I found an issue with the save/open handlers of `ipc_file_io`, where errors weren't properly sent back to the renderer, so we silently hid save errors, among other things. We no longer do that.
Fixes #876.
> Harmonize our IPC call naming

- src/api/log.js
- src/api/log/format.js
We'd like to suppress logs if we've logged the same (sans timestamp) recently, because there are parts of Chrysalis that can be very noisy otherwise. To this end, implement a simple suppressor, that keeps a cache of the last few logs, and suppresses new messages that have been seen recently. Any log that goes through the suppressor will be added to the cache, regardless of eventual outcome, so we always have the last N most recent ones in there.
The suppressor keeps the cache size small and tidy, defaulting to a convenient two lines.
This, in turn, makes the `focus.find()` logs far less noisy, even on disk.
> api/log: Implement a simple log suppressor

- src/api/log.js
- src/api/log/transports.js
Winston's built-in Console transport is simple, but has a major drawback: it transports everything via `console.log`, formatted as our formatters decided to. However, for Chrysalis, we'd like a different format on the browser console than in files, logged at the appropriate levels, and the log info as a javascript object, rather than stringified JSON.
The BrowserConsole transport implemented herein does just that.
**Winston's transport.Console**:
**BrowserConsole**:
> api/log: Implement our own browser console transport

- src/api/log.js
- src/api/log/transports.js
- src/main/ipc_logging.js
To ease development, create a symlink to the current log file on startup, and also cull old files, so they don't accumulate endlessly. We keep the last 10 only.
Fixes #911.
Requires - and includes - #915.
> logging: Create a symlink to the current log & cull old ones

- src/renderer/screens/Preferences.js
- src/renderer/screens/Preferences/MyKeyboard.js
When we're in context (when we have unsaved changes, on the MyKeyboard tab), prevent changing tabs, as that would silently discard pending changes. We now need to either save those changes, or discard them, before we're allowed to leave the MyKeyboard tab.
Fixes #918.
> Preferences: Disallow changing tabs when in context

- src/renderer/screens/Editor/Macros/MacroEditor.js
React wants a unique key for things it handles, including macro step components. For existing steps, we were using `step.id` as a key, but newly added steps did not have such a property, and we ended up with an empty key, which React complained about.
To fix this, add an id to newly created steps, and use a key for our macro steps that can never be empty.
> MacroEditor: Add a step id  to newly added steps

- package.json
- src/renderer/screens/SystemInfo.js
- yarn.lock
I don't feel *super* strongly about this, but 
is pretty hard to follow.
With this PR,
becomes
> Let our json pretty printer print lines up to 1k long in systeminfo dumps to make them default to a more compact, more scannable format

- src/renderer/screens/Preferences/keyboard/KeyboardLEDPreferences.js
- src/renderer/screens/Preferences/keyboard/leds/DefaultLedMode.js
We have lifted out the default led mode configuration on the Kaleidoscope side into a new plugin. This updates the DefaultLEDMode component accordingly.
> Preferences: Update the default led mode component to match Kaleidoscope

- src/renderer/screens/Preferences/ui/LookAndFeelPreferences.js
The state should only be updated when the selected language is different from the current language.
Fixes #928 
Signed-off-by: Bruno Chevalier <BrunoChevalier@users.noreply.github.com>
> Fix bug where language selection menu can be stuck when switching between different languages

- src/renderer/App.js
- src/renderer/screens/LayoutCard.js
- src/renderer/screens/Preferences/ui/LayoutEditorPreferences.js
Instead of trying to initialize the host keyboard layout when rendering LayoutCards or Preferences, do so in App, and make sure we _load_ the available layouts first.
This guarantees that the layout will be properly set for every screen, including the layout editor.
Fixes #932.
> Initialize the host keyboard layout early, in App

- src/renderer/i18n/en.js
- src/renderer/screens/LayoutCard.js
- src/renderer/screens/Preferences/ui/LayoutCardsPreferences.js
By default, the layout card screen shows - and prints - layers continously, avoiding page breaks within a layer, but having as many layers per page as it can fit. However, when one wishes to print layout cards, it is often desirable to print only one per page.
This patch introduces such a setting. When enabled, it will add a `breakAfter: "page"` CSS property to each layer, enforcing a page break after each one.
Preferences preview:
> LayoutCard: Add an option to print only one layer per page

- src/main/index.js
- src/main/ipc_exit.js
- src/renderer/components/Header.js
- src/renderer/components/MainMenu/MainMenu.js
When we're quitting, we want to ask for confirmation first, if we have pending changes, rather than silently - and quickly - lose them. To do this, we catch the `before-quit` event in the main process, and unless we were already told to quit, we'll send a message to the renderer, and stop the quit process.
The renderer, upon receiving the `app.should-quit?` event, can decide how to proceed: either send an `app.confirm-quit` message back, so the main process will quit immediately, or send an `app.stop-quit` message, handle any confirmation necessary, and then restart the quit process as needed.
The main process does set a one second timer before sending the `app.should-quit?` message, in case the renderer is crashed or otherwise unresponsive. When the timer is up, we'll quit. Sending an …
> Before quitting, ask for confirmation if there are pending changes

- package.json
- src/api/focus/keymap/.gitignore
- src/api/focus/keymap/db.js
- src/main/index.js
- src/main/ipc_cldr.js
- tools/precompile.mjs
- tools/precompile/cldr_data.mjs
We still import cldr from the renderer process, for `cldr.extractLanguageDisplayNames`, but that hopefully doesn't expect to be in a node environment.
If it does, we'll have to push it (along with the cldr data) to the main process.
Fixes #924.
> Pregenerate the CLDR data, rather than loading it from the renderer

- src/main/ipc_device_discovery.js
- src/renderer/i18n/en.json
- src/renderer/screens/KeyboardSelect/LinuxPermissionsWarning.js
We need `/run/udev` to be able to scan devices, so if it is not accessible, or doesn't exist, we will now display a useful error message.
Fixes #700.
> linux: If /run/udev is not accessible, give a useful error message

- src/renderer/App.js
- src/renderer/index.js
Because setting the theme modifies state, if we do that from the renderer function, we need to do it from a `useEffect`. While there, move `migrateDarkModeToTheme()` from App's renderer to index.js. We only need to do the migration once, not on every render, so it didn't make sense to have it in App anyway.
> Move the initial theme setup into a useEffect

- src/api/flash/index.js
- src/api/focus.js
- src/api/hardware-ez-ergodox/index.js
- src/api/hardware-keyboardio-atreus2/index.js
- src/api/hardware-keyboardio-model01/index.js
- src/api/hardware-softhruf-splitography/index.js
- src/api/hardware-technomancy-atreus/index.js
- src/renderer/ActiveDevice.js
- src/renderer/i18n/en.json
- src/renderer/screens/FirmwareUpdate.js
- src/renderer/screens/FirmwareUpdate/FirmwareChangesDialog.js
- src/renderer/screens/FirmwareUpdate/FirmwareSelect.js
- src/renderer/screens/FirmwareUpdate/FirmwareVersion.js
- src/renderer/screens/FirmwareUpdate/FlashSteps.js
- src/renderer/screens/FirmwareUpdate/UpdateDescription.js
There were multiple complaints against the firmware update screen, and this redesign addresses most of them. The goal was to simplify the screen, reduce the amount of unnecessary information displayed at a time, while also showing useful information we did not show before.
With this redesign, the update instructions are no longer shown directly on the firmware update screen. Instead, when one selects the "Upload" or "Factory reset" actions, the popup dialog will show the instructions instead. Previously, clicking on "Upload" started the process immediately without confirmation - now we ask for confirmation in this case too. Both in order to be able to display the instructions, and to avoid accidentally triggering the process. See below for additional screenshots.
Then, the dropdown that …
> Firmware upgrade/redesign

- src/api/focus.js
Until #985 is properly fixed, add a small delay between requests to avoid triggering the bug. This is not a correct solution, but it is one that makes Chrysalis usable on the Model100 until a real fix is found.
> api/focus: Temporarily add a small delay between requests

- package.json
- src/main/index.js
- src/main/ipc_firmware.js
- src/renderer/ActiveDevice.js
- src/renderer/App.js
- src/renderer/components/GlobalContext.js
- src/renderer/hooks/useFirmwareAutoUpdate.js
- src/renderer/i18n/en.json
- src/renderer/screens/FirmwareUpdate.js
- src/renderer/screens/FirmwareUpdate/FirmwareChangesDialog.js
- src/renderer/screens/FirmwareUpdate/FirmwareSelect.js
- src/renderer/screens/FirmwareUpdate/FirmwareUpdateWarning.js
- src/renderer/screens/Preferences/ui/AutoUpdatePreferences.js
- static/build-info.yml
Modeled after the application update mechanism, the firmware file auto-update works in a similar way: if the feature is enabled (it is disabled by default), it will check what's the latest version of the firmware on GitHub, and if it's more recent than the version we ship with, and more recent than whatever we have previously downloaded (if anything), then it will download the new bundle and extract it.
The Firmware Update screen will ask the main process for the version, changelog, and base directory to use for the default firmware. If firmware auto-update is enabled, the main process will check first try the downloaded files, and only fall back to the shipped version if we have nothing downloaded yet.
If firmware auto-update is disabled, then we won't even check if there's a new …
> Implement a firmware file auto-update mechanism

- src/renderer/screens/LayoutCard.js
Don't just pass down the custom names for the keymap renderer, use the custom name for the page header too, if a custom name is available.
> LayoutCard: Use custom layer names for the header too, if available

- src/renderer/screens/Editor/Sidebar/Overview.js
To allow the rest of the cells some more space to display, restrict the layer name column to 33% of the total.
This is most visible on the Atreus:
> Editor/Overview: Make the layer names cell a little shorter

- src/api/hardware-ez-ergodox/components/Keymap.js
- src/api/hardware-keyboardio-atreus2/components/Keymap.js
- src/api/hardware-softhruf-splitography/components/Keymap.js
- src/api/hardware-technomancy-atreus/components/Keymap.js
- src/api/hardware-technomancy-atreus/components/keymap/Key.js
- src/renderer/screens/Editor/Sidebar/Overview.js
When preparing the custom layer names pull request, I seem to have dropped the patch during a rebase that added support for custom layer names to keyboards other than the Model01 and the Model100. The first patch in this series does just that, modifies the keymap renderers to use custom layer names if available.
The second part is a change to the Overview widget on the sidebar, so it renders the label with custom layer names too.
Both together fix #1003.
> Fix custom layer name displays on the Overview & non-Model01/100 devices

- src/renderer/i18n/en.json
- src/renderer/screens/FirmwareUpdate/FirmwareVersion.js
In case we can't detect the firmware version, display a default saying so, rather than having a bit of empty space. Also display a suitably sized skeleton box while the version is being retrieved.
> FirmwareVersion: Display a default when the firmware version is unavailable

- src/renderer/hooks/useFirmwareAutoUpdate.js
The `useFirmwareAutoUpdate` hook was initially copied from `useAutoUpdate`, and as part of the process, it set the `updateAvailable` state on the global context. That's unrelated to firmware auto-updates, and the hook should not touch it at all, so this patch removes that.
The result of the mistake was that whenever there was a firmware update, Chrysalis' main sidebar also showed an "Apply update & restart" menu item by mistake. With the hook not fiddling with state it has no business with, this is no longer the case.
> FirmwareAutoUpdate: Do not pretend an app update is available

- src/renderer/screens/Editor/components/LegacyAlert.js
When the LegacyAlert component was lifted out, it was lifted out as if it was a function within the renderer, rather than a component. As such, it was expecting to receive the onClick handler directly, rather than a prop.
As it is a component which receives props, lets make it aware of that, and use `props.migrateLegacy`, so the handler actually gets called.
Fixes #988.
> Editor: Fix the onClick handler of LegacyAlert

- src/api/focus/keymap/db.js
When switching layouts, wrap the new code table with `withModifiers()`, to add modifier augmented keycodes to it, too. This, in turn, will make the code following this update these modifier-augmented keycodes according to the new table.
In practice, this means that if the host layout is set to, say, US Dvorak, then keys like `Ctrl+Y` will render as `Ctrl+Y`, rather than `Ctrl+T` (`T` is the same keycode on Qwerty as `Y` is on Dvorak).
Fixes #993.
The PR also removes a bit of code rendered obsolete by pre-processing the CLDR files. Without removing that branch, we'd have to do the same thing there, too, while it would never be called.
> api/focus/keymap: Update modifier-augmented key labels too when switching layouts

- src/main/menu.js
- src/renderer/App.js
- src/renderer/i18n/en.json
When printing finished (or rather, whenever Electron decides to call our callback), display a notification about whether the print finished, or error'd. No notification is displayed if the print is canceled.
Fixes #996.
> After printing, display some kind of feedback

- src/api/focus.js
As long as this function existed, it was practically a no-op, it succeeded as long as there was at least one USB device connected, of any kind. It did not perform adequate checks to see if the requested VID/PID pair is among them.
This worked, because the flashing process rebooted the keyboard before checking for the presence of a bootloader, so by the time we went to check, it was always there anyway.
Things fell apart as soon as the function was supposed to do a real check. This patch makes it do what it was always supposed to do: iterate over the devices found, and only return success if the desired one is among them.
> api/focus: Make waitForDFUBootloader actually perform a check

- src/renderer/ActiveDevice.js
- src/renderer/App.js
- src/renderer/screens/FirmwareUpdate.js
When trying to flash a keyboard that is already in bootloader mode, Chrysalis was bombing out, because it was trying to pull `focusDeviceDescriptor` from `activeDevice.focus` - but when connected to a keyboard in bootloader mode, we do not have an `activeDevice`, let alone `activeDevice.focus`. However, the descriptor is readily available in `FirmwareUpdate` (the sole user of `activeDevice.defaultFirmwareFilename()`), so move the function back there, where we have all the information at hand.
This stops Chrysalis from bombing out there.
Additionally, when trying to disconnect from a keyboard, if there is no `activeDevice`, don't try to use it.
These two changes together fix flashing when started while the keyboard is already in bootloader mode.
> Fix flashing when starting from bootloader mode

- src/renderer/components/MainMenu/MainMenu.js
- src/renderer/screens/FirmwareUpdate/FirmwareVersion.js
When Chrysalis is connected to a keyboard that is in bootloader mode, this PR fixes two smaller issues:
- The FirmwareUpdate page will display "Firmware version unavailable" instead of a `<Skeleton>` that is in forever-loading state
- The Layout Cards menu item in the Main Menu is no longer displayed for keyboards in bootloader mode
> Small UI fixes when connected to a keyboard in bootloader mode

- src/renderer/screens/LayoutCard.js
`useEffectOnce`, just like `useEffect` itself, needs a plain, non-async function. So instead of using doing initialization directly in the effect, push it into an async function called _from_ the effect. The same pattern we use elsewhere.
This gets rid of an error printed on the dev console when leaving the Layout Cards screen.
> LayoutCard: Don't use an async function directly with useEffectOnce

- src/api/focus/keymap/db.js
We want to present the list of supported layouts grouped by their language (or if that is unavailable, the language code, or group), and the groups should be alphabetically sorted too.
To achieve this, we need to sort the list the same way we group them.
Addresses another issue identified in #649, namely that Chinese is no longer sorted *after* English, and the groups are alphabetically sorted by language, rather than by language code.
> api/focus/keymap: Sort supported languages the same way we group them

- src/renderer/components/GlobalContext.js
- src/renderer/components/Header.js
- src/renderer/screens/LayoutCard.js
When printing layout cards, the header does not add any useful information, but takes up space - and colors - on the first page. Lets not show the header when printing the layout card screen.
We do show it for everything else.
Fixes #943.
> Hide the Header when printing Layout Cards

- tools/precompile/cldr_data.mjs
This corrects the two problems identified in #1014:
- `shift+foo?+bar?`-style mappings are now recognised as shifted mappings
- when loading a layout from the `osx` set, swap E00 and B00
With these changes, the Croatian layout is correct on OSX, and it is as close to being correct on Windows and Linux as we can be, given our sources. Sadly, the chromeos mappings are unusable for us, and there's no Croatian layout for Windows in CLDR, so OSX is our closest match of a source, and the best we can do, given the source data we have.
> Assorted CLDR parsing fixes

- src/renderer/screens/Preferences/ui/LayoutEditorPreferences.js
The preview updates when a layout is chosen. It does not auto-update while the dropdown is open, only when a selection is made. Mostly for technical reasons, and because updating with the dropdown open would be a *lot* of small changes quickly rendered, which I find annoyingly distracting.
This still allows one to preview the layout without having to go visit the layout editor screen.
> Preferences: Add a preview of the selected keyboard layout

- src/api/focus/keymap/db/modifiers.js
Originally, `withModifiers()` was only called internally by the keymap db, so it could safely assume that the list of keys it receives will fall within the standard HID range, and can have modifiers applied safely.
However, with 62f6ba5034abcd31d71d38ff9a4f2f40be39f433, that is no longer the case, and `withModifiers()` will be called with a keylist that can potentially include already augmented keys.
It should only augment keycodes in the base HID range, and if it encounters a keycode in the source list that is an augmented key, that should be ignored in favour of the newly augmented ones.
Fixes #1026.
> api/focus/keymap: withModifiers() should not apply mods to non-standard keys

- src/renderer/components/ConfirmationDialog.js
- src/renderer/i18n/en.json
- src/renderer/screens/FirmwareUpdate.js
With the combination of our current flashing instructions, the "Cancel / Ok" pair of buttons aren't exactly clear, they do not accurately convey what will happen if either of them is pressed.
Changing them to "Abort / Continue" makes it clearer - I hope - what they are for: one to abort the whole flashing operation, the other acknowledges the instructions, and tells Chrysalis to proceed.
I intentionally avoided using "Upload" for the confirmation label, because that'd just repeat what's on the button that popped this dialog up in the first place.
Fixes #1023.
> FirmwareUpdate: Change the confirmation dialog's confirmation label to Continue

- src/api/focus.js
on windows and linux when we send more data than it can handle.
@algernon if this behaves basically ok for you on linux, let's get it pushed out asap for folks
> A temporary workaround for the Model 100 getting wedged

- src/renderer/screens/FirmwareUpdate.js
This is a followup for 577dee8678a124bfe3343e79adca83ec6b6518e3, where we changed the label of the firmware update confirmation dialog from "Ok" to "Continue". This does the same for the "Update with factory reset" case too.
> FirmwareUpdate: Change the factory reset confirmation label to Continue

- src/api/hardware-keyboardio-atreus2/components/Keymap.js
When deciding whether to display the main legend of a key on the Keyboardio Atreus in a bigger size or not, ignore if there's a `hint` legend, it doesn't matter.
Fixes #1033.
The Keyboardio Atreus is the only device that has this feature. Everywhere else, we do not play with font sizes, so they don't need a similar adjustment, either.
> hardware/atreus2: Display the main legend in big letters if it's a single letter

- src/api/focus.js
- src/renderer/i18n/en.json
- src/renderer/screens/Preferences/keyboard/PluginPreferences.js
- src/renderer/screens/Preferences/keyboard/plugins/SpaceCadet.js
This adds support for toggling SpaceCadet on and off (and saving that setting), and setting the global timeout. Requires the `SpaceCadetConfig` plugin from keyboardio/Kaleidoscope#1234.
While both SpaceCadet and SpaceCadetConfig support a "no delay" mode, Chrysalis does not, and will display the "no delay" mode the same as the normal active mode.
> Preferences: SpaceCadet support

- src/renderer/i18n/en.json
The Editor screen uses the term "Sticky keys" for OneShot keys, lets use the same for the Preferences screen.
> Preferences: Use the same terminology for "OneShot" as on the Editor

- src/api/focus.js
When we're writing request parts, we want the firmware to expect more data, so we should not try to drain it, because that signals to the firmware that we're done writing, while we really aren't.
If we signal we're done writing, the firmware may end up terminating the processing of an in-flight command, or even misparse the data it receives.
One of the problems observed was that when saving a keymap, we ended up with seemingly random corruption in various places. Research confirmed that this happened due to Chrysalis splitting a keycode halfway through, and due to the drain, the firmware interpreted that as two distinct keycodes. Thus, the key where the split occurred, and the one after were wrong, and the keys after were shifted one key.
Without the drain, the firmware will expect more …
> @api/focus: Do not drain the serial port while writing request parts

- .github/ISSUE_TEMPLATE/bug_report.md
Use the correct name for the "Report a problem" screen. Add key shortcut description for opening Developer Console on macOS.
Fixes #1063.
> improve bug report template

- src/renderer/breaking-news.js
- src/renderer/breaking-news/firmware-0.90.1.js
- src/renderer/components/BreakingNews.js
- src/renderer/i18n/en.json
- src/renderer/screens/KeyboardSelect.js
Due to the importance of the 0.90.1 firmware, display a breaking news section just below the application bar for Model 100 owners, urging them to update their firmware. The news item is dismissable, and if dismissed, will not be shown again (future breaking news will be shown, however). Clicking the button leads to [my post](https://community.keyboard.io/t/model-100-firmware-update-to-fix-corruption-issues/5553) on the forums.
The banner is not displayed if no Model100 is detected.
Improvements to the displayed message would be most appreciated!
> Display breaking news for Model 100 owners on the keyboard selection screen

- src/main/ipc_firmware.js
- src/renderer/hooks/useFirmwareAutoUpdate.js
- src/renderer/screens/Preferences/AutoUpdate.js
Unlike the auto-update for Chrysalis itself, firmware auto-update is not destructive, and is considerably more useful, even desirable. As such, turn it on by default.
Existing settings will not be touched, this is for new installs only.
> Enable firmware auto-update by default

- src/renderer/screens/Preferences/MyKeyboard.js
- src/renderer/screens/Preferences/keyboard/AdvancedKeyboardPreferences.js
- src/renderer/utils/clearEEPROM.js
When using `eeprom.erase` to restore factory settings, the keyboard will erase the eeprom and reboot before sending us a reply. We can't await for that to return, as it never will.
While we could - and should - fix the firmware, we still want to handle older firmware, so we need a Chrysalis-side solution too. This solution is  to wait 10 seconds in `clearEEPROM()`, and just return. Ten seconds should be enough to clear the eeprom, even if we're using a pretty large emulated storage where writes are slow. They're not *this* slow.
With this, the factory reset in Preferences will eventually complete. Since we enforce a reboot afterwards, this factory reset will now disconnect from the keyboard as well, and land us back on the Keyboard Selection screen.
Fixes #1056.
> When using eeprom.erase, return after 10 seconds

- src/api/focus/layernames.js
- src/renderer/i18n/en.json
- src/renderer/screens/Editor/Editor.js
- src/renderer/screens/Editor/components/LayerNamesStorageAlert.js
> Prevent saving & display an alert when layernames take too much space

- src/api/hardware-keyboardio-model01/components/keymap/Key.js
It's not good, but it's better than the status quo ante.
> Clean up how we render the edges on Model 100 keys

- src/api/hardware-keyboardio-model01/components/keymap/Key.js
> Backport the logic we use on the Atreus for showing larger text sizes on keys in Chrysalis

- src/api/hardware-keyboardio-model01/components/keymap/Key.js
Make palm key stroke width wider to compensate for the different tranformation used for these shapes. Also slightly increase the stroke width for other keys.
Fixes #1062.
> improve key outlines

- src/api/focus.js
Using `this.close()` clears properties that we need elsewhere, in `handleDeviceDisconnect()` in App.js. With those properties cleared, the handler over there can't do its job properly. If it can't do its job properly, then we're not handling the disconnect either, which leaves other parts of Chrysalis in a bad state, where they assume the keyboard is connected while it is not.
Since we do have a way to handle disconnects, at a higher level, lets let it do that, and not close the device at a lower level.
Fixes #1107.
> api/focus: Do not close the port when receiving a close event

- src/renderer/App.js
- src/renderer/i18n/en.json
- src/renderer/routerHistory.js
- src/renderer/screens/SanityCheck.js
When starting up, perform some sanity checks, to verify that Chrysalis is running in an environment that allows it to function correctly. Among other things, we verify that the Electron version we're running against is the expected one, and that static files bundled with the package are accessible.
If any of the sanity checks fail, a message is displayed, urging the user to use an official build. The user can still navigate away, if they choose to do so, the message is only shown once on startup.
This is mostly here to combat the `chrysalis` package in AUR, which is causing a lot of frustration and support requests.
> Perform some sanity checks during startup

- src/api/focus/keymap/db/base/dualuse.js
- src/renderer/screens/Editor/Sidebar/Modifiers.js
- src/renderer/screens/Editor/Sidebar/SecondaryFunction.js
Fixes both of the issues mentioned in #1117:
- When a key is set as a dual-use modifier, it is no longer shown as a modifier a few sections above: ![Screenshot from 2022-09-29 21-18-27](https://user-images.githubusercontent.com/17243/193123004-3361ac6e-dd40-48d7-b03d-a7792768341c.png)
- Added the rest of the right-hand side modifiers to dual-use modifiers: ![Screenshot from 2022-09-29 21-18-32](https://user-images.githubusercontent.com/17243/193123274-e67466fe-89e0-4d7e-bae8-477e1411d524.png)
The right-half modifiers do overflow most keycaps, but that's a different issue.
> Couple of fixes for secondary action modifiers

- src/renderer/screens/Editor/Editor.js
In case the `LayerNames` plugin is not enabled firmware-side, getting the stored size of the layer names still returns a non-zero value. We need to check if there is *any* storage size, before comparing the serialized length, otherwise we mistakenly disable saving (and don't even show a warning, because the warning correctly checks for the presence of the plugin).
Fixes #1119.
> Editor: Do not disable saving if LayerNames is not in use

- src/styles/keymap.css
Being able to select text is in general a desirable feature. However, in case of the keymap, being able to do so is distracting, annoying, and not useful at all. This little change disables that, preventing one from selecting the *text* of key labels. It does not prevent selecting the buttons themselves, of course.
This change is to prevent this from happening (the blue selection highlights):
> styles/keymap.css: Disable user-select for the keymap SVGs

- src/renderer/screens/Editor/Editor.js
When changing layers, we need to set the selected key again, to point to the same index on the target layer, otherwise the keymap will show the correct data, but the sidebar will not.
Fixes #1122.
> Editor: When changing layers, ensure that the selected key is in sync

- static/udev/60-kaleidoscope.rules
Without this patch systemd-udevd.service log warnings:
```
systemd-udevd[496]: /etc/udev/rules.d/60-kaleidoscope.rules:13 ENV key takes '==', '!=', '=', or '+=' operator, assuming '='.
systemd-udevd[496]: /etc/udev/rules.d/60-kaleidoscope.rules:13 ENV key takes '==', '!=', '=', or '+=' operator, assuming '='.
systemd-udevd[496]: /etc/udev/rules.d/60-kaleidoscope.rules:14 ENV key takes '==', '!=', '=', or '+=' operator, assuming '='.
systemd-udevd[496]: /etc/udev/rules.d/60-kaleidoscope.rules:14 ENV key takes '==', '!=', '=', or '+=' operator, assuming '='.
…
```
> udev rules: ENV doesn't support := operator

- src/api/focus/colormap.js
- src/renderer/components/Toast.js
- src/renderer/screens/Editor/Sidebar/Colormap.js
- src/renderer/screens/Editor/Sidebar/Overview.js
- src/renderer/screens/Preferences/keyboard/KeyboardLayerPreferences.js
This is a small collection of fixes for various scenarios that could result in a white screen. With these fixes applied, I am no longer able to reproduce the bugs I've been seeing before.
The fixes in this PR include:
- A race condition existed in `Preferences / My Keyboard / KeyboardLayerPreferences`, where we tried to use the keymap data before the initialization step for the component finished. This was corrected by not trying to use the keymap data before the component is fully loaded.
This bug was very hard to actively trigger, but happened fairly often randomly.
- Fixed a problem in `@api/focus/colormap`, where it bombed out when the Colormap plugin was enabled, but no storage was reserved for it. It will now treat that case as not having the plugin enabled. (Fixes #1151)
- Fixed a …
> Assorted fixes for different whitescreen scenarios

- src/renderer/ActiveDevice.js
When removing data from the cache, we need to delete the entire key, not just set it to undefined. When set to undefined, the key still remains in the cache, so `command in this._cache` will happily return true.
Not properly deleting the whole thing could result in returning `undefined` to callers after a save, instead of pulling the data from the keyboard again.
Fixes #1155, and possibly a number of similar issues we didn't discover yet.
> ActiveDevice: When removing from the cache, delete the entire key

- src/api/focus/keymap.js
When pulling the keymap from the keyboard, handle the case where either the built-in, or the custom keymap are zero-sized. Instead of raising an exception, treat these as if the keymaps were empty.
> api/focus: Guard keymap pulling against zero-sized keymaps

- src/renderer/screens/Editor/Sidebar/Overview.js
The Overview footer was only displayed in the past when we had empty layers. The "Copy layer" and "Paste layer" buttons were later added to the same footer - but the condition on displaying the footer remained intact. This resulted in these buttons disappearing when we had no empty layers.
Lets display the footer unconditionally, and only do the hiding logic for the empty layer toggle button.
Fixes #1162.
> Editor: Always show the "Copy layer" and "Paste layer" buttons

- src/renderer/screens/Editor/Editor.js
It is not required for a device to have any colormap-related functionality, whether it has LEDs or not. Copying and pasting layers should function regardless of the presence of colormaps.
As such, make `copyLayer()` handle the case of a missing colormap correctly, and do not require colormap for `hasCopiedLayer()`.
With these fixes, it is now possible to copy & paste layers on an Atreus.
Originally reported on the [forums](https://community.keyboard.io/t/chrysalis-how-to-copy-and-paste-layers/5750/5?u=algernon).
> Editor: Layer copy & paste should not depend on Colormap

- src/renderer/screens/Editor/Editor.js
After pasting a layer, show the context bar, too. Setting the `modified` state alone does not display the context bar. Being "in context" allows the user to cancel the changes, and it also prevents exiting Chrysalis and losing changes.
Fixes #1175.
> Editor: Show the context bar after pasting a layer

- src/api/flash.js
- src/api/focus.js
These changes are meant to improve the flashing problems we're seeing, and address #1060, #1078, and possibly others too.
Without these changes, I am able to reproduce #1078 with 100% reliability on Linux (but not on Windows or macOS). With the patches, I can't reproduce it on either.
I've also reproduced - reliably - multiple problems on Windows: one where we failed to reconnect after flash, and another where we succeeded, but failed to reconnect after the eeprom wipe. This patchset appears to fix those too.
I have tested the changes on all three platforms, with and without chunked writes on all three of them, and they worked every case, multiple times in a row.
On the other hand, it doesn't feel great that we're still finnicky when it comes to timing. The reason these issues were …
> Improve the robustness of flashing a little

- .github/workflows/pull-requests.yml
- tools/pr-number
- tools/preinstall.js
Lately, we have been seeing - and creating - pull requests where user testing and feedback would be of incredible value. However, building from source is a barrier we don't want to put in front of potential testers.
For this reason, lets build and publish artifacts for pull requests aswell. They will not be signed - because we have no control over what gets built, really -, and they will not be uploaded to GitHub. They are made available nevertheless, and the workflow is set up so that it posts the URLs after the build to the originating pull request.
> CI: Add a workflow to build & publish unsigned pull request artifacts

- tools/precompile/cldr_data.mjs
Unfortunately, the windows set of layouts we use by default does not have a Colemak layout. Fortunately, the macOS (neé osx) set does, so lets pull it from there, along with the Croatian layout we were already pulling.
Fixes #1150.
> cldr: Pull the Colemak layout from the osx set

- src/renderer/screens/Editor/Sidebar/BlankKeys.js
- src/renderer/screens/Editor/Sidebar/BrightnessKeys.js
- src/renderer/screens/Editor/Sidebar/Colormap.js
- src/renderer/screens/Editor/Sidebar/CustomKey.js
- src/renderer/screens/Editor/Sidebar/LayerKeys.js
- src/renderer/screens/Editor/Sidebar/MediaKeys.js
- src/renderer/screens/Editor/Sidebar/Modifiers.js
- src/renderer/screens/Editor/Sidebar/MouseKeys.js
- src/renderer/screens/Editor/Sidebar/OneShotKeys.js
- src/renderer/screens/Editor/Sidebar/SecondaryFunction.js
- src/renderer/screens/Editor/Sidebar/VolumeKeys.js
- src/renderer/screens/Editor/components/CategorySelector.js
- src/renderer/screens/Editor/components/Collapsible.js
The driving logic behind the auto-close/auto-open behaviour of collapsible sections turned out to be more confusing than useful. Implementing a behaviour that is intuitive and not confusing, is bordering the impossible, so lets not try that.
This patch removes the functionality altogether: collapsible sections will start off being closed, but once opened manually, they will stay open.
Fixes #1159.
> Editor/Sidebar: Remove the auto-close/auto-open behaviour

- .github/workflows/build.yml
- .github/workflows/lint.yml
- .github/workflows/pull-requests.yml
Update all actions we use where a new version is available.
This addresses most of #1169, with only `samuelmeuli/action-electron-builder` remaining. Unfortunately, that action appears abandoned, so we'll have to figure out something else about it at some point.
> ci: Update most of the Actions we use

- src/renderer/screens/Editor/Editor.js
- src/renderer/screens/Editor/Sidebar.js
- src/renderer/screens/Editor/Sidebar/LayoutSharing.js
- src/renderer/screens/Editor/Sidebar/Overview.js
When importing the colormap, we're importing both the palette, and the colormap, but we were importing them in two steps, both of which were asynchronously setting the same state. This resulted in the two async state changes stomping on each others feet, and corrupting the colormap.
To remedy this issue, add a new helper that can set them both at the same time, and thus, we avoid the race condition.
Fixes #1059.
> Fix the colormap importing via backup & restore

- .github/workflows/pull-requests.yml
Because the publish step requires secrets that are unavailable for pull requests, we can't - and don't want to, either - run the publish step, because it would fail. As such, skip the step instead.
This does reduce the usefulness of building artifacts for each PR, but they remain useful for PRs originating from the Chrysalis repo, so it is still worth keeping.
> ci: Only run the publish step for PRs when the source repo is ours

- src/renderer/screens/Editor/Sidebar/LayoutSharing.js
Due to an earlier change, importing from backups made during flash are not importable via the "Backup & Restore" mechanism. Since the import was half-broken in this case anyway, lets disable this feature for now, until we develop a proper fix.
Addresses #1201 - but doesn't fix it.
> LayoutSharing: Do not offer backups for import for now

- src/renderer/App.js
Wrap the internal content of the DnD provider in a <div> to stop theapp from blowing up on keyboard disconnect.
Solution based on https://github.com/remix-run/react-router/issues/8834
> Wrap the internal content of the DnD provider in a <div>

- src/renderer/config.js
In development mode, the static path must be a relative path, and in production builds, it needs to be relative to `__dirname`, otherwise static files will not be found.
This fixes - among other things - the ChangeLog screen.
> renderer/config: Fix the paths returned by getStaticPath()

- src/api/focus/keymap/db/modifiers.js
- src/renderer/i18n/en.json
- src/renderer/screens/Editor/Sidebar/Modifiers.js
- src/renderer/screens/Editor/Sidebar/SpecialModifiers.js
This PR prevents a collision with DynamicMacros key range.  For example, DM#0 has keycode 53596.  Without this PR, this displays as "C+Ƨ+{" and the macro can't be edited.
This PR:
1. Prevents generating modifier combinations that include `topsyturvy` with other mods.  This avoids the display issue where DynamicMacros \#0-9 decoded to TopsyTurvy+Control.
2. In the Modifiers tab, disables the TopsyTurvy radio button when any other mod is selected, and vice versa.  This prevents the user creating invalid combinations.
This is a quick follow-up to PR #1379, addressing issue #1378.
> TopsyTurvy cannot be combined with other mods
