keyboardio/Chrysalis

src/errors/errors.js, src/renderer/App.js
Signed-off-by: Paul Jones <thepauljones@gmail.com>
=> Helpful error for outdated firmware

src/errors/errors.js, src/renderer/App.js
i.e. you didn't click a key but entered a keycode
=> Return from onKeyChanged if the keyIndex is -1

src/renderer/index.js, src/renderer/mockup/components/App.js
Signed-off-by: Paul Jones <thepauljones@gmail.com>
=> When enabling alternative UI there were a couple compile errors

src/renderer/__snapshots__/App.test.js.snap, src/renderer/components/Dashboard.js, src/renderer/components/KeyboardSelect.js
Adds a report issue button to the dashboard, and a report issue badge to the keyboard selector.
=> Report issue link

src/renderer/__snapshots__/App.test.js.snap, src/renderer/components/KeyboardSelect.js
=> KeyboardSelect: Add a "Scan devices" button

src/renderer/components/KeyboardSelect.js
=> KeyboardSelect: Don't disable the "Scan devices" button, ever

src/renderer/components/LayoutEditor/KeySelector.js
=> KeySelector: Add a dropdown indicator to the key type menu

src/renderer/components/LayoutEditor/KeySelector.js
Fixes #64.
Not perfect yet, but it does allow one to change unknown keycodes, so a definite improvement.
=> KeySelector: Implement a way to modify unknown keycodes

package.json, src/renderer/components/KeyboardSelect.js, yarn.lock
It's not perfect, but it gets the job done for now.
=> Initial support for the ErgoDox

src/renderer/components/FirmwareUpdate.js
=> FirmwareUpdate: Don't offer a factory firmware if there's none

src/main/index.js
=> main/index: Open devTools on Ctrl+Shift+I

package.json, src/renderer/App.js, src/renderer/components/SaveChangesButton.js, src/renderer/i18n.js, src/renderer/i18n/en.js, src/renderer/i18n/hu.js, src/renderer/screens/ColormapEditor.js, src/renderer/screens/FirmwareUpdate.js, src/renderer/screens/KeyboardSelect.js, src/renderer/screens/LayoutEditor.js, src/renderer/screens/Settings.js, src/renderer/screens/Welcome.js, yarn.lock
This moves all the translatable strings (at least those that are within Chrysalis itself) into a single file, then we add Hungarian translation, and a new setting on the settings page to switch between available languages. Fixes #152.
The settings page looks ugly, but it gets the job done. We'll need to design a proper settings page at some point.
=> Localisation support & Hungarian translation

src/renderer/i18n/en.js, src/renderer/i18n/hu.js, src/renderer/screens/Settings.js
This is a redesign of the Settings screen, modeled after Chrome's settings page, lacking a better example.
=> Settings page redesign

src/main/index.js
=> main: Add Ctrl-R (reload) & Ctrl-Q (quit) key bindings

src/main/index.js
We're scaling down much better now, so removign the minimum requirements is now an option.
=> Remove the minimum window size requirement

src/renderer/App.js
Swap Settings and KeyboardSelector in the sidebar, moving Settings down, just above the divider.
=> App: Move the Settings menu down

src/renderer/i18n/en.js, src/renderer/i18n/hu.js
=> Remove the "#" from layer names

src/renderer/App.js
=> This adds the Chrysalis version to the sidebar

.travis.yml, package.json, tools/get-artifact, tools/preinstall.js, tools/s3-upload.js
This adds a Travis CI control file, which will build Linux, Windows and OSX packages. I have not tested the artifacts yet, but native builds worked so far, so here's hoping...
The results are not published anywhere yet.
=> Automatic builds on push

NEWS.md, package.json
Updated the version in `package.json`, and wrote NEWS items for 0.4.0.
=> Preparations for 0.4.0

src/renderer/App.js, src/renderer/components/ConfirmationDialog.js, src/renderer/i18n/en.js, src/renderer/i18n/hu.js, src/renderer/screens/Editor.js
=> App: Ask for confirmation before discarding unsaved changes

src/renderer/App.js, src/renderer/screens/Preferences.js
When changing the language of the application, save the choice, and restore it on startup.
=> Preferences: Save the language setting

src/renderer/screens/Editor.js
=> Editor: Dim read-only layers a little

src/renderer/i18n/en.js, src/renderer/i18n/hu.js
This should better describe what reconnect is useful for.
Fixes #218.
=> Welcome: Update the description of reconnect

package.json, src/main/index.js, yarn.lock
Add electron-window-state
Set default window size to 1200x900
Set to save window size and position on exit and restore on startup
Solves: #368
=> Add electron-window-state

src/renderer/i18n/en.js, src/renderer/i18n/hu.js, src/renderer/screens/FirmwareUpdate.js
This partially addresses #276.
=> FirmwareUpdate: Add a troubleshooting link to the error message

README.md
Put the download buttons into their own section, for easier discovery.
Fixes #414.
=> README: Highlight the download buttons better

src/renderer/screens/Editor/Editor.js
Fixes #451
⚠️ This is my first contribution to this project. Patience and feedback appreciated 🙂
For context, this was last touched in #405.
=> Allow importing JSON with empty colormap

README.md
=> Update the list of supported hardware in README

src/renderer/components/MainMenu/MainMenu.js
So we can expire the discord links to combat spam
=> Switch to a redirect-based discord invite

src/api/keymap/db/mediacontrols.js
Signed-off-by: Romain Heller <Rom1deTroyes@users.noreply.github.com>
=> Support more XF86 Keycodes

package.json, src/renderer/screens/Editor/ImportExportDialog/ImportExportDialog.js, yarn.lock
This is not an end goal, but is a little bit nicer than the status quo
=> Switch to a more compact json stringification.

package.json, src/api/flash/chrysalis-flash-raise.js, src/api/flash/index.js, src/api/flash/raiseFlasher/arduino-flasher.js, src/api/focus/index.js, src/api/hardware-olkb-planck/index.js, src/api/log/index.js, src/renderer/App.js, src/renderer/components/MainMenu/MainMenu.js, src/renderer/components/MainMenu/SystemInfoMenuItem.js, src/renderer/i18n/en.js, src/renderer/i18n/hu.js, src/renderer/screens/Editor/Editor.js, src/renderer/screens/Editor/ImportExportDialog/LoadDefaultKeymap.js, src/renderer/screens/SystemInfo.js, src/renderer/utils/installUdevRules.js, yarn.lock
This adds a new screen to Chrysalis, which allows one to let Chrysalis collect information about the system (OS, Chrysalis itself, and any connected device) and bundle that up in a zip file they can send us.
Clicking the "Collect Information" button will gather the info, and then pop up a save dialog:
At the moment, the following files are included in the zip file:
```
❯ unzip -l chrysalis-debug.bundle.zip
Archive:  chrysalis-debug.bundle.zip
Length      Date    Time    Name
---------  ---------- -----   ----
321  2020-10-08 12:23   osInfo.json
20  2020-10-08 12:23   chrysalis.json
34849  2020-10-08 12:23   logs.json
24319  2020-10-08 12:23   device.json
---------                     -------
59509                     4 files
```
```json
{
"platform": "linux",
"distro": "Debian GNU/Linux", …
```
=> System info screen

.travis.yml, tools/get-artifact, tools/s3-upload.js
To make it easier to test branches, build and upload artifacts for them too. We still do not want to do that for PRs, but for branches pushed to the repo, we do.
=> travis: Do automatic builds & uploads for branches too

src/renderer/components/ColorPalette/ColorButton.js, src/renderer/components/LoadingScreen.css, src/renderer/screens/Editor/Sidebar/LayerKeys.js, src/renderer/screens/Editor/Sidebar/MacroKeys.js, src/styles/keymap.css
Fix for bug https://github.com/keyboardio/Chrysalis/issues/609 - "Chrysalis + Atreus +  Move to layer exposes nonexistent layers"
Husky's pre-commit hooks would nag me about another file I didn't touch, so I ran prettier.
=> Issue 609 nonexistent layers

src/renderer/components/Header.js, src/renderer/screens/Editor/Editor.js
=> Fix the z-index of the hardcoded/EEPROM layer mix warning

src/renderer/i18n/en.js, src/renderer/screens/Editor/Sidebar/Overview.js
=> Editor/Overview: Add a short explanation for the Overview table

src/renderer/screens/Editor/components/CategorySelector.js, src/renderer/screens/Editor/components/KeyButtonList.js
=> Clean up the display of categories in the key list

src/main/index.js, src/renderer/screens/Editor/Sidebar/Overview/LayoutSharing.js, src/renderer/screens/SystemInfo.js
And also sneak in a ux improvement to the systeminformation bundle
=> Fix our save dialogs

.babelrc, package.json, src/renderer/screens/KeyboardSelect.js
Use a nice modern javascript feature that will let us reduce a bunch of ugly code that makes code harder to read and write.
=> Optional chaining

src/renderer/screens/FirmwareUpdate.js
=> Fix the "flash firmware" UI to be centered

src/api/hardware-keyboardio-model01/components/Keymap.js, src/renderer/screens/Editor/Editor.js
@algernon I think this is a priority fix.
=> Fix the Model 100 UI to not be black on black. 

src/main/index.js, src/main/ipc_backups.js, src/main/ipc_file_io.js, src/renderer/i18n/en.js, src/renderer/screens/Editor/Sidebar/Overview/LayoutSharing.js
To make our backups more useful, offer loading the layout from them on the backup & restore screen.
=> Editor/LayoutSharing: Offer loading layouts from backups, too.

src/renderer/screens/ChangeLog.js
Add a little vertical margin so that the Card shadow does not appear cropped.
=> ChangeLog: Add vertical margins

static/Keyboardio/Model100/layouts/colemak.json, static/Keyboardio/Model100/layouts/dvorak.json, static/Keyboardio/Model100/layouts/qwerty.json
Copied from the Model01 verbatim.
Fixes #847.
=> Model100: Add a layout library for the Model100 too

src/api/focus.js
We can attach an id to every request, and because we'll be using callbacks to return the results, we can attach the same id to the response as well. This makes it trivial to match requests with responses.
To make that even easier, both timeout and success will now log the original request too.
Example:
```json
{
"label": "focus",
"level": "verbose",
"message": "response",
"request": {
"args": [],
"command": "plugins",
"id": 21
},
"response": "EEPROMKeymap\nColormapEffect\nMacros\nMouseKeys\nMagicCombo",
"timestamp": "2022-06-04T01:34:18.203Z"
}
```
=> api/focus: Attach an id to every request, and track it in the response

src/api/focus.js
One major problem with `DelimiterParser` was that it only emitted data when the delimiter was found, it was buffering meanwhile. This meant that if we wanted to reset our timeout when partial data came in, we could not. We also built half of a custom parser in the `data` event handler of the parser.
This patch replaces our use of `DelimiterParser` with our own, custom parser that is explicitly tailored to the Focus protocol, and our own use case.
The new parser buffers an entire Focus response, rather than buffering line by line. While buffering, it is running a timer, which gets reset every time we receive data, and it gets cleared when we receive the stop marker. In practice, this means that we no longer wait for N milliseconds for the entire response to arrive, but N milliseconds …
=> api/focus: Implement our own custom parser

src/main/index.js, src/main/ipc_system_info.js, src/renderer/screens/SystemInfo.js
System Info is one of the things we do in the renderer that we really *should* be doing in the main process. this fixes that. (We should be doing the logs over there too)
=> System info to main proc

src/renderer/i18n.js, src/renderer/i18n/nl.js
Signed-off-by: Bruno Chevalier <BrunoChevalier@users.noreply.github.com>
=> Add translation for Dutch and enable Dutch in i18n

src/main/ipc_device_discovery.js, src/renderer/i18n/en.json, src/renderer/screens/KeyboardSelect/LinuxPermissionsWarning.js
Reverts keyboardio/Chrysalis#962 See #967
=> Revert "linux: If /run/udev is not accessible, give a useful error message"

src/renderer/App.js
the async method in an inner body.
=> useEffect can't have an "async" method as its body. you need to stick

src/renderer/screens/KeyboardSelect.js
=> useEffectOnce isn't designed to accept promises/async functions. This was causing errors on startup

src/renderer/screens/Editor/Macros/MacroEditor.js
=> setSteps needs to be inside a callback

src/renderer/hooks/useAutoUpdate.js
=> Add a missing dependency setUpdateAvailable to the useAutoUpdate useEffect

src/api/focus.js
Chrysalis tries its best to serialize requests and responses, but under some circumstances (more on that later), we can end up with receiving data out of band. When that happened, and we did not have a callback set - which we didn't -, then our `data` event handler ended up erroring, which bubbled up as an unhandled exception.
This was most noticeable when upgrading a 0.10.4 (or earlier) firmware on a Keyboardio Atreus to 0.11 or later. We dropped one layer in 0.11, so when upgrading and restoring layers, Chrysalis sent a 480 item keymap to the firmware, but the firmware replied with a `.` after 432 items. This - for reasons I do not understand at this time - resulted in Chrysalis emitting a number empty responses, not just one, thus, triggering the scenario where we were missing …
=> api/focus: Handle situations where we have incoming data without a callback

src/api/flash/DFUProgrammerFlasher.js, src/api/flash/DFUUtilFlasher.js
We're having problems flashing the Model100 on Windows, and I *suspect* it is because we fail to launch `dfu-util` due to being packed up. However, we do not know that, because we don't have an `error` handler for the spawned child process. This PR adds that, so we'll be able to see what exactly happens.
=> api/flash: Capture and log errors when trying to spawn a child process

static/Keyboardio/Model100/layouts/colemak-dh.json
Thanks to @superfell for building it!
=> Model100: Include a Colemak DH layout

src/renderer/screens/SystemInfo.js
=> Change our default debug bundle name to something possible to attach to a github ticket.

src/renderer/i18n/en.json, src/renderer/screens/FirmwareUpdate.js
Fixes #1085 
@algernon - please test this one out before merging. Just in case
=> Change how we let users perform a full factory reset, making the option more prominent.

src/api/focus/keymap/db/base.js, src/api/focus/keymap/db/base/lang_intl.js, src/api/focus/keymap/db/base/platform_apple.js, src/renderer/i18n/en.json, src/renderer/screens/Editor/Sidebar.js, src/renderer/screens/Editor/Sidebar/LanguageKeys.js, src/renderer/screens/Editor/Sidebar/PlatformAppleKeys.js
[this should go in release notes]
=> * Add support for Apple's Screen Lock, Globe, Exposé and Mission Control keys.

src/renderer/i18n/en.json, src/renderer/screens/FirmwareUpdate.js, src/renderer/screens/FirmwareUpdate/FirmwareSelect.js
=> The existing firmware update screen is very verbose and not very space efficient.

src/renderer/i18n/en.json
=> clarify color picker instructions

src/api/focus.js, src/api/focus/keymap/db/base/mousekeys.js, src/renderer/ActiveDevice.js, src/renderer/hooks/usePluginEffect.js, src/renderer/i18n/en.json, src/renderer/screens/Editor/Sidebar/MouseKeys.js, src/renderer/screens/Editor/components/KeyButton.js, src/renderer/screens/Preferences/components/PreferenceWithHeading.js, src/renderer/screens/Preferences/keyboard/PluginPreferences.js, src/renderer/screens/Preferences/keyboard/plugins/MouseKeys.js
Fixes #525 and #1174.
Also adds the new mousekeys commands to the list of commands to back up & restore during flash.
=> Add Mouse Key configuration support to Preferences

src/main/ipc_firmware.js
Even though Chrysalis does not download snapshot firmware if Chrysalis itself isn't a snapshot, it still offered *previously* downloaded snapshot firmware on the Firmware Update screen.
To remedy this issue, the backend will now check the version of any downloaded firmware, and skip over it if its a snapshot version while Chrysalis is not.
Fixes #1195.
=> Do not offer snapshot firmware on release versions of Chrysalis
